### ISSUE TITLE
Take away temporarliy the link to the My Question page

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#108]
@giovanisp  raised the important #103 :

the page vilfredo.org/questions/mine  has to be implemented and linked in the user menu:

![image](https://cloud.githubusercontent.com/assets/180794/5599681/e8cd4402-92cb-11e4-9250-ef36e112de28.png)

And this should be out for next release. In the meantime the link should be absent (commented) so people do not get confused. In fact it could be greyed with a popup that says that this feature is coming soon :-). This might raise expectations.

**Comment by pietrosperoni** [comment]
Works, closing it

**Comment by pietrosperoni** [comment]
Just tested, the Question link is still there.

Please delete it or make it really obvious that it does not work. Right now it does not work but it is not greyed, and it looks like a bug.
![screen shot 2015-01-14 at 11 37 34](https://cloud.githubusercontent.com/assets/1333674/5738167/26fd62a2-9be1-11e4-9ec9-d01f465a6e3c.png)

**Comment by giovanisp** [comment]
I vote for hiding any menu item that is not implemented yet. Let's keep it clear.

**Comment by derekpa** [comment]
It should be greyed out on test. Where are you seeing it?

**Comment by pietrosperoni** [comment]
Ok, in the test it is greyed out. I was testing on nightly. My understanding was that nightly and test were equivalent. Was I wrong?

@giovanisp I agree that it should be clean. Having things greyed out with the writing "coming soon" is also an option to raise expectations. In any case for this version is ok like this. Then we need to decide for next version. I keep it open but move it to next version.

**Comment by pietrosperoni** [comment]
No, I close it. Let's keep it clean :-).

**Comment by derekpa** [comment]
Since we're using test now for fixes needed review it will be updated more often than nightly, for obvious reasons.

**Comment by pietrosperoni** [comment]
Well, if a fix is from more than 24 hours before it should be on nightly :-)
