### ISSUE TITLE
Links in the text should be automatically noticed and transformed

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#109]
If someone writes a link in a question, it should appear as a link, opening a page in an alternative tab. Not so in the proposals, to make sure proposals are self contained.

Example where this is not happening:
![screen shot 2015-01-03 at 11 42 07](https://cloud.githubusercontent.com/assets/1333674/5602189/4e3cc648-933d-11e4-9c76-152aec8c61ff.png)

**Comment by pietrosperoni** [comment]
Yes, that works :-)

**Comment by giovanisp** [comment]
What is done and will be release in 2.0 is being moved in github to 2.0 milestone. I think we are close to ship.
