### ISSUE TITLE
present the final proposal solution and runner-ups clearly and in an understandable way for users

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#11]
Top Core Feature
(specs)

**Comment by pietrosperoni** [comment]
Ok, the results page, should complete this version.
@derekpa 

We need a simple final page after a single generation.

Next to the "move on to writing" which should be greyed for now. There should be a button:

"Move on to the results". Here we have several cases:

If we have a single proposal in the Pareto Front, this have reached consensus:

Return that proposal as the winner. And just say, we have a winner. And that is...

If we have multiple proposal in the pareto front but they all were voted by everybody in the community then all those proposals reached consensus:

 Then order them (and only those proposals in the pareto front) in order of the median of how much they were appreciated (median of the horizontal value). And say that the winner is the first one. And the other are also good proposals.

If no proposal reached consensus, then take the proposals in the pareto front and say:
Then show all the proposals in the Pareto Front in order of appreciation and write:
No proposal so far reached consensus. Those are the proposals that represent the community. Everybody is represented here. We suggest them in order... (and then present them)

And this will do for now.

**Comment by derekpa** [comment]
Should we not also add a button to end the question, ie take it out of the writing/voting loop?

**Comment by giovanisp** [comment]
Oh yeah definetly. As of 2.0.0-rc1 questions are "one generation only". So if the user ends voting, the question is closed.

**Comment by derekpa** [comment]
Well then moving to writing after voting should itself end on the results page without the need for a button.

**Comment by giovanisp** [comment]
Ok.

**Comment by pietrosperoni** [comment]
Ok, I saw the case where there is a consensus and one proposal wins and works well. I will put the images as I text:
![screen shot 2015-01-25 at 08 46 12](https://cloud.githubusercontent.com/assets/1333674/5890802/f9db990c-a46d-11e4-8dee-6435a438b1cb.png)
Later I will do the others

**Comment by derekpa** [comment]
Screen Shot 2015-01-25 at 10.56.00.png

An example of two winners

**Comment by derekpa** [comment]
![screen shot 2015-01-25 at 10 56 00](https://cloud.githubusercontent.com/assets/1368533/5891960/e6c36398-a4a6-11e4-9599-b854ee6ddee5.png)

An example with two results

**Comment by giovanisp** [comment]
@pietrosperoni  is that good for now for now (rc1) ?

**Comment by pietrosperoni** [comment]
yeah, good enough. We will add a visual graphical representation in the next release rc2
