### ISSUE TITLE
Double email navigation problem 

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#110]
Related to #67 I sent myself an invite with a second email address. 
The email arrived. When I opened it I followed the link but was still logged in, and as a result I ended up being present in a question two times with the same name.

To avoid that, let's do like LinkedIn. It asks you to create a new account or in alternative, login with an existing account and add the email in their account first then accepting the invitation. So the user has both mails linked.

**Comment by derekpa** [comment]
The obvious fix was to check that the person who's accepting the email invitation is already added, so don't just don't add them again, but tell the sender the user emailed has previously accepted an invitation for this question.

**Comment by giovanisp** [comment]
"I sent myself an invite with a second email address. "  in the sense that I was first invited using a@b.com and then invited c@d.com .. both are emails of mine but Vilfredo trated them as two separate persons. My suggestions was to link both a@b.com and c@d.com in my profile, so when I get invited via any of those addresses, I am shown as myself only. Does that makes sense to you ?

**Comment by derekpa** [comment]
@giovanisp OK, I see, So that's adding an extra feature. 

But what you highlighted before was a bug I needed to fix. You said, "to avoid this" [getting added twice] let's copy LinkedIn. Whereas the way to avoid it was actually just a simple fix to the code.

If we want to add this new feature - sure, why not -  then its for reasons other than fixing the problem of being added twice.

That was my point. Make sense?

**Comment by giovanisp** [comment]
yes, you're right.
let's make this a new feature for next release.

**Comment by derekpa** [comment]
So can we close this or not? I've tested it but technically you should test it too.

Is there a good way to create a new issue for the new feature which will tie to this issue?

**Comment by giovanisp** [comment]
created a new feature for next release
