### ISSUE TITLE
When you invite a person on demo it does not receive an invitation

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#115]
If you invite someone to a question, and write their email address, they receive an email. 

The same thing does not happen if you invite a person through the first part of the form, where you click on the checkbox of a specific person.
![screen shot 2015-01-05 at 14 56 33](https://cloud.githubusercontent.com/assets/1333674/5613846/905a73be-94ea-11e4-81cc-e47182908e01.png)

I have written a question on 404 and invited both @derekpa and @giovanisp and none participated. On the other side there is a question written by @giovanisp which I can see (thus I must have been invited) but I never received any invitation.

A person should receive both an email invitation and an online notification, methinks.

**Comment by derekpa** [comment]
For now a user is added immediately and an email is sent informing them they have been added to the question. As I said in email we will have to change the process so an invite is sent which can be accepted or not.

**Comment by pietrosperoni** [comment]
@derekpa could you please fix this without me opening another issue? :-). I put away the needs review for now (by the way works perfectly. Now I know what should I work on)

**Comment by derekpa** [comment]
You put away the needs review for now? What do you mean?

**Comment by derekpa** [comment]
Yes, Done should NOT say cancel. It means Done, I'm done here, close modal.

I shall include instructions. Click Done when finished adding users.

**Comment by pietrosperoni** [comment]
You click Add users.
Then it opens a window with the name that you could add.
You click on the names you need to add and now you have some name clicked, and under it there are two buttons, <DONE> and <ADD USERS>. The Done one is blue.

So I click the Blue button thinking that in this way the people will be added, and I am done.
Except that now the people are NOT added. And instead everything you have done is ignored.

This sounds ok to you @derekpa ?
And no, it should NOT include instructions. Is just a form, and it should be intuitive enough. This is counterintuitive, sorry. If you do not believe me I can ask my father to open a question and invite me. I record him, and then you'll see ;-)

So one button means: 
close this form without adding the users (the one is currently on the left and says DONE)

The other button means:
close this form adding the users (the one currently on the right and says ADD USERS).

This is not ok, sorry :-)

**Comment by giovanisp** [comment]
open a new issue for enhancement. that screen must be redesigned following google docs invitation screen as we agreed in a previous meeting.

**Comment by pietrosperoni** [comment]
ok
