### ISSUE TITLE
The Button Move on to Writing should not appear until at least 2 people have voted.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#117]
This is how a question appeared in the voting phase before anyone has voted:

![screen shot 2015-01-09 at 10 56 40](https://cloud.githubusercontent.com/assets/1333674/5677990/be9182da-97ed-11e4-9c26-c2a4d5b3daaa.png)

It should also say how many people have voted on how many questions. Like the old table but only with the column of Number of Proposals voted.

In fact can you insert back the table, @derekpa ? What were the column? Maybe we could keep some.

**Comment by derekpa** [comment]
Yes, I knew about this. A lot of these 'bugs' are just things still to do, because I can't complete everything at once if I want to make regular commits.

Can't remember the columns offhand.

**Comment by pietrosperoni** [comment]
Ok, so it goods if this remains open for as soon as you have the time :-)

**Comment by pietrosperoni** [comment]
I started testing it but hit another bug

**Comment by pietrosperoni** [comment]
Hit the bugs #125 and #126

**Comment by pietrosperoni** [comment]
Nop, on nightly it still does not work. RIght now no one has voted and the button is there:
![screen shot 2015-01-17 at 11 48 12](https://cloud.githubusercontent.com/assets/1333674/5788705/35e04c94-9e3e-11e4-8c4d-4fecea867384.png)

**Comment by pietrosperoni** [comment]
Sending it back to @derekpa

**Comment by pietrosperoni** [comment]
Just tested it, and it seem to work on test.
But then the button does not do nothing. (Maybe we never actually programmed the second generation)

**Comment by giovanisp** [comment]
I think it is better that we end 2.0.0 with one generation, and a list of results. Then in the list of results this button will be grayed out as "coming soon"

**Comment by pietrosperoni** [comment]
:+1: Yes, but we should make a results page. i see if I can write up a basic page structure this night

**Comment by derekpa** [comment]
"But then the button does not do nothing. (Maybe we never actually programmed the second generation)"

Yes we did :-) Moving to writing moves on the generation and displays the pareto from the previous voting round as inherited proposals and presents again the possibility to write new proposals.

**Comment by derekpa** [comment]
Results page was done a while ago. The button appearing after 2 voters is done too, but button hidden for now till we introduce 2nd gen.

**Comment by giovanisp** [comment]
@pietrosperoni, why not apply here the same principle for moving to voting? The user could move to writing after 1 vote (his own) in case he is reordering his priorities.


Inviato da iPad

**Comment by pietrosperoni** [comment]
I wasn't aware we were already doing the second generation. Yes, of course. In any case it is just a constant. We can change it at any time.

**Comment by giovanisp** [comment]
We aren't... This issue is not about implementing the multi-generation,conly about showing or hiding the button according to a given number of votes (0, 1 or >1 ?)

**Comment by pietrosperoni** [comment]
Ok, I am lost. WHat is the point of showing the button at all if there is no new generation to go to?

Are wel discussing all this just to decide if we are showing a greyed button :-)

:-D

**Comment by giovanisp** [comment]
Yes... I remember you proposed somewhere else to leave things grayed out to convey a "coming soon" message to users... So we were asking to apply it here as well.
I wouldn't show anything, anywhere. Your take. :-)

**Comment by pietrosperoni** [comment]
Let's not worry about this. Soon we are going to have the new generation, and at that point we add it.
