### ISSUE TITLE
Voting is not working

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#118]
Please see:

https://dl.dropboxusercontent.com/u/2754299/VotingNotWorking.mov

**Comment by derekpa** [comment]
There was another bug with moving on from writing to voting. I pushed the fix to test.

See if it works now.

Also, you were clicking too fast in the video. Click once and wait and see if the vote appears. The broadband or Dreamhost might be slow.

**Comment by pietrosperoni** [comment]
Yes, now it works. Thanks
