### ISSUE TITLE
Redesign the invitation following the google doc model.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#119]
Following the discussion on #115,
redesign the demo as in google doc.

ALSO, in the meantime change the <DONE> Button into a button that explains that the person are not going to be invited.

@giovanisp is this ok? Can You explain to Derek how to do it, since I seem to be unable. Thanks.

**Comment by derekpa** [comment]
Your english isn't that bad, Pietro :-)

As I said before, for the moment I will change the other button to 'close' so it's quite clear.

**Comment by pietrosperoni** [comment]
nop. Close will STILL mean that people expect their decision to be saved.

**Comment by derekpa** [comment]
Actually there is nothing to save. When you click Add Users the names disappear from the list.  You didn't notice this?

I know this is just a first version to get things working, but I thought it was obvious.

When you send email invites, they are sent. There's nothing to save.

**Comment by pietrosperoni** [comment]
It does not happen, Derek. I click on the checkbox and the name has a checkbox signed. But then the name does not get added. Do I have to make a video to show you?

**Comment by giovanisp** [comment]
I will work in a mockup as soon as I can, sorry but at the moment can't. This one is a bit more complicated than the "vote" button...

**Comment by derekpa** [comment]
OK Pietro, I thought it was quite clear. You set the permissions, check the boxes the users you want to add, then click the Add Users button.

**Comment by derekpa** [comment]
I'll make it clearer

**Comment by pietrosperoni** [comment]
Ok, let me know when I should test it.

**Comment by derekpa** [comment]
Its on test. I was going to add a feedback message too to make it even clearer, but have a look. I think its OK for this release.

**Comment by pietrosperoni** [comment]
Please, assign it to me, @derekpa

**Comment by pietrosperoni** [comment]
yes, much better!
