### ISSUE TITLE
please assign issues to me and add "needs review" when issues needs to be reviewed

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#120]
SO I can search them easily. And do them, and close them

**Comment by giovanisp** [comment]
ok

**Comment by pietrosperoni** [comment]
@derekpa , please close this as soon as you read it, so we know you read it too :-)
(yes, another one closed for 2.0.0 !)

**Comment by derekpa** [comment]
Ah, well then surely  they should be assigned back to who created he issue in the first place so they can test it.

**Comment by pietrosperoni** [comment]
Sure. Assign it to whoever should test it. It's just that right now we are in 3 and since we pay Giovani while I work "for free" I rather do it myself if I can :-)
