### ISSUE TITLE
please separate DB's for all environments..

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#123]
This is very important. Demo right now is being used, and we cannot have errors appearing in that page.

**Comment by pietrosperoni** [comment]
More generally as @giovanisp said in #124: 
>please separate DB's for *all environments*...

**Comment by derekpa** [comment]
This is already the case. I had copied a snapshot from the demo to he test site for testing a fix.

I can leave it or put the original test snapshot back.

**Comment by pietrosperoni** [comment]
No, I think this is great. There is plenty to test with. Just let us know, so we don't get confused. :-)

**Comment by derekpa** [comment]
Well I thought that which is why I just kept it.
