### ISSUE TITLE
There should be a way to edit and delete a proposal

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#124]
I just made a second proposal, because I did not realise that test and demo were using the same DB.

**Comment by pietrosperoni** [comment]
![screen shot 2015-01-16 at 17 28 33](https://cloud.githubusercontent.com/assets/1333674/5780768/11078ba6-9da5-11e4-98c7-b60af157bcb1.png)

**Comment by giovanisp** [comment]
please separate DB's for *all environments*...

**Comment by pietrosperoni** [comment]
Copying your requesto to #123

**Comment by derekpa** [comment]
tets and demo are not using the same DBs.

**Comment by pietrosperoni** [comment]
I just tested it. It's just that Test was created out of Demo. You are right. Sorry, @derekpa , I did not know it. And was confused to find the same questions on both.

Still, the issue of editing and deleting a proposal is still alive, though.

**Comment by derekpa** [comment]
Sure, that was definitely on the todo.

**Comment by giovanisp** [comment]
can we deliver tomorrow @derekpa ?

**Comment by pietrosperoni** [comment]
Ok, works. Great
