### ISSUE TITLE
on nightly if there are two proposals from two different people it is not possible to go to voting

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#126]
Not sure why

![screen shot 2015-01-17 at 11 17 10](https://cloud.githubusercontent.com/assets/1333674/5788633/ed0b2e5c-9e39-11e4-9120-8f59a48d7db7.png)
![screen shot 2015-01-17 at 11 17 28](https://cloud.githubusercontent.com/assets/1333674/5788632/ed08d0f8-9e39-11e4-9131-052e8bfdf2fd.png)

**Comment by pietrosperoni** [comment]
I registered with Pietro, invited Pietro3. Registered with Pietro3. Accepted the invitation (from another browser). Then wrote a proposal with Pietro and a proposal with Pietro3. So now there are two proposals. But Pietro still does not see the button to move on to voting.

**Comment by pietrosperoni** [comment]
In fact I just wrote a second proposal from Pietro3 and I still cannot move on from Pietro. I suspect the system waits for 2 proposals from the person that started the question

**Comment by pietrosperoni** [comment]
And in fact as soon as I wrote the second proposal from the owner of the question I can now move on. So this is definitely a bug

**Comment by giovanisp** [comment]
Do we even have to force the question author to write a solution? There might be use cases where the author has no idea of what solution to propose...

**Comment by derekpa** [comment]
There's no mystery. I'm just using the wrong proposal count. I need to download the actual count for the question.

**Comment by pietrosperoni** [comment]
ok, and this solves the mystery of the proposal not moving forward. :-)

**Comment by pietrosperoni** [comment]
Yes, now this move on correctly
