### ISSUE TITLE
Add a "privacy policy" link for a policy page in the footer

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#127]
To launch we need a first version of privacy policy. We need to tell which data is collected and for what reasons, including research for new algorithms, if so.

**Comment by pietrosperoni** [comment]
@giovanisp I tried to write it using this: http://www.freeprivacypolicy.com/ but failed at some point. Maybe you could do this. If not we need to ask @Franz739

**Comment by pietrosperoni** [comment]
I also should ask Anthony on this. Maybe there is a standard Privacy Policy we need to implement to work with the NHS

**Comment by pietrosperoni** [comment]
Anthony told me to refer to: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/350099/1_NHS_TC_Guidance.pdf

also: "I don’t think there’s a specific standard privacy policy - I would not imagine that the email issue you raise would be a big problem. The issues that do arise are about clinical data which our system and yours wouldn’t be handling."

**Comment by giovanisp** [comment]
ok. @derekpa  can you put a link "Privacy Policy" in the footer that points to  /privacy  page (http://nightly.vilfredo.org/privacy) ?

The footer will become like:

© 2009-2015 Pietro Speroni & Derek Paterson    [Report Issue](#) | [Privacy Policy](#)

**Comment by pietrosperoni** [comment]
Also my name could be Pietro Speroni di Fenizio 
:-)

**Comment by giovanisp** [comment]
For the page content, once the page template HTML is in place I can populate with something simple in the lines of http://epetitions.direct.gov.uk/privacy-policy

**Comment by pietrosperoni** [comment]
just put "email" in plural :-)

**Comment by giovanisp** [comment]
I have committed the link footer, but @derekpa I need you to create the blank html page for /privacy and the routing rule to have  test.vilfredo.org/privacy working, so I can proceed with adding the text.

**Comment by derekpa** [comment]
OK, done

**Comment by giovanisp** [comment]
Ok, thanks. Ps.: LESS is not compiled on test... I don't see my latest changes.

**Comment by pietrosperoni** [comment]
@derekpa are you pulling changes from other people (Giovani in this case)?

**Comment by giovanisp** [comment]
Please see my LESS commits.
