### ISSUE TITLE
fix html5 w3c validation errors in 2.0.0

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#131]
As of now page is not validating as HTML5 correctly. 
http://validator.w3.org/check?uri=http%3A%2F%2Fnightly.vilfredo.org%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

**Comment by giovanisp** [comment]
Still does not validate, but small issues are left behind, let's move them to next final.

**Comment by derekpa** [comment]
Yes, it should. Sorry, I forgot to update nightly. Corrections added to test as usual. Try validating that.

**Comment by derekpa** [comment]
Ah, OK, it DID validate then the apple links you added broke it.

**Comment by giovanisp** [comment]
ok for apple links, they won't validate but do not break the page (vendor-specific tags).
