### ISSUE TITLE
Too many people in the system makes it impossible for the system to add new people

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#134]
OOops, this might be important.

When the list of names in the system grows too much, the window to add new users grows so much it becomes impossible to scroll. But under it there is the edit bar to add people. Making it impossible to add people. (I needed it to test the simple auto additction of people).

![screen shot 2015-01-22 at 15 31 33](https://cloud.githubusercontent.com/assets/1333674/5857335/24d789ec-a24b-11e4-900a-409f4f42978c.png)

Temporary quick and dirty solution:
for now just put the edit box above in the page, and add a scroll bar on the side.
(If you have a better solution use that).

I am adding this to this release. I know it is crazy, but if this does not work, they cannot use it.

**Comment by derekpa** [comment]
ok i allow the whole  modal to scroll up. Should do for now.

**Comment by pietrosperoni** [comment]
ok tested. Good enough for now
