### ISSUE TITLE
email in the link should not be understandable

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#135]
When you invite someone the email is in the clear in the URL.
This is often seen as a privacy issue. And many people criticised mtgox for this (they also put the password in the clear... :-) ).

![screen shot 2015-01-22 at 15 53 17](https://cloud.githubusercontent.com/assets/1333674/5857725/403479ae-a24e-11e4-895b-6428c26ce467.png)

@giovanisp how important is this? I put it as enhancement for next versions. You decide

**Comment by giovanisp** [comment]
we really don't need to send the email in the URL. We can use the invitation token (which I suppose is in the DB) to recover the email address.

**Comment by derekpa** [comment]
Yes, that's not needed. Not sue why I put it there really. Copying other websites....

**Comment by giovanisp** [comment]
If you are doing this, see also the related issue on the pretty url for invites  ..../i/....

**Comment by derekpa** [comment]
which issue is that?

**Comment by giovanisp** [comment]
I'll look into it ...
Is the email already removed from links, so we can close this issue ?

**Comment by giovanisp** [comment]
@derekpa the issue for pretty url is on vilfredo-core  fairdemocracy/vilfredo-core#43

> change the link to:  Click to participate: https://vilfredo.org/i/0e0c654353be4f55bc6293c915610f67
> https for security and avoid useless redirect and /i/ for "invitation" .. shorter and cleaner.

**Comment by giovanisp** [comment]
This issue is open in the core  fairdemocracy/vilfredo-core#42
