### ISSUE TITLE
If someone is invited on a question while he is logged in the invitation should appear

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#136]
I was logged in as Pietro in browser 1
logger in as Pietro3 (email pietro3@) on browser 2
Pietro3 also have email pietro91@ associated to it.

Pietro invited pietro91@ to the question, but no notice appeared. I don't know if this is because pietro91 is a secondary email, or because no notifications appear in general

**Comment by giovanisp** [comment]
is this a bug ?

**Comment by derekpa** [comment]
No idea. Problem is very badly described. I'd put on hold at the moment.

**Comment by pietrosperoni** [comment]
The title says it all. When you are online, and someone invites you, something should pop up and let you know you have been invited. So people does not need to rely on emails

**Comment by giovanisp** [comment]
Well ... that would go into "notifications"... in later relase right ?

**Comment by pietrosperoni** [comment]
Yes.
