### ISSUE TITLE
triangle zooming is not working well

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#137]
from #86:

>4) when a person sees the triangle at different zoom levels (zooming in or out of a page, for example if he has a very big monitor, or a very small one, or he cannot see very well) the triangle size does not change in a smooth way.

>It was always the zoom problem. The problem was that the triangle did not look nice in my screen. And the reason (in retrospect I realise) is that I practically never keep the 100% zoom but usually the 120% zoom so I do not need glasses. It's just that it was not clear at the time.

**Comment by pietrosperoni** [comment]
Won't fix. This we fix when we do the triangle on canvas #156
