### ISSUE TITLE
Decide when the RC2 release should be

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#140]
A lot of things were not done for RC1. But now we inserted another release between RC1 and 2.0.1. In a sense this is a failure because this makes everything one more step away.

@giovanisp when should the next release be? We should also have this info with the RC1

**Comment by giovanisp** [comment]
I would aim for one minor release each 15 days. But that can happen only after we have a proven method to release core and client versions aligned. Tomorrow we can see how much work it takes. Also, remember that from tomorrow onwards each change impacting the database has to be scripted in an upgrade script for data migration, and demo updated a couple of days before the release to test bed the software before going live. 
For this reason I think rc2 won't be ready before 20-30 days from tomorrow onwards (consider also feedback from curious users, eventually).

**Comment by giovanisp** [comment]
Ps. You are right about start planning next releases in a schedule. So I went ahead and gave estimated date for our next releases, 1,2,6 months, 1 year and 5 years ("maybe someday"). For 1 and 5 years vision to work, we have to grow the community.

**Comment by pietrosperoni** [comment]
Great, I would simply take away the "maybe one day" date. The idea for it is of a repository of things that we can take and use in any moment. Usually way before that date.

**Comment by pietrosperoni** [comment]
But if we could get the 2.1 with everything that entails (groups, cycles, and so on) by June I would be very happy. In fact this is very good. I can now start to add issues for things further away

**Comment by giovanisp** [comment]
The amount of stuff delivered per release would be best calculated using Agile points and measuring "team velocity" (which I think github does not handle). So i cannot say exactly what we can get by June, unless we keep working and fine tuning the milestones. It also depends on growing development efforts if can fund them and maximize the benefits in terms of code and architecture quality.
