### ISSUE TITLE
automatic domain url redirect from "http" to "https"

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#144]
maybe from the control panel it is possible to force https access (that is the server will redirect any http call to the respective https page). This improves security.

**Comment by pietrosperoni** [comment]
not via the control panel. At least not in any obvious way. I also searched the https://discussion.dreamhost.com/ but could not find any reference. Apparently is possible to do it via .htaccess

**Comment by pietrosperoni** [comment]
Unless you want to do it @giovanisp , in which case self assign it to yourself :-)

**Comment by giovanisp** [comment]
here's the .htaccess needed:

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by giovanisp** [comment]
@derekpa  is this ok for live ?

**Comment by derekpa** [comment]
Yes, I will add it.

**Comment by derekpa** [comment]
Added, and runs like a well oiled redirecting machine.
