### ISSUE TITLE
checklist of "don'ts" for iOS tablet webapp design

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#152]
need to make sure that the release don't do or use the follow:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/CreatingContentforSafarioniPhone/CreatingContentforSafarioniPhone.html#//apple_ref/doc/uid/TP40006482-SW21

**Comment by giovanisp** [comment]
duplicate of #153

**Comment by pietrosperoni** [comment]
@giovanisp , we have a Duplicate label :-)
