### ISSUE TITLE
Being able to upload one (or more) pictures in the proposals.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#162]
This is very important. One of the main uses of Vilfredo is to let people chose between different creative options. Different logo, different furniture for a house, different images that should represent you on a social network, and so on. In fact images are the most simple and direct applications of Vilfredo.

So we should give the possibility to people to upload an image.

**Comment by giovanisp** [comment]
We could think of providing "image-only" option. No doby test allowed, just the title and 1 file upload per proposal. Of course they could still create questions allowing text+images proposals.

**Comment by pietrosperoni** [comment]
Eventually we want to give both the possibility to put the text and the image(s). 
But I like the idea of having questions where only image-only options are allowed. It would in a sense simplify a lot. But then would it make sense to have "understand" "I do not understand" option? Shouldn't be just a horizontal line?

Also it could be that some question types are only possible with the non free version.

In any case I would say for now we could have that each proposal could be just a question. And let's live it at that :-). What do you think?

**Comment by giovanisp** [comment]
"each proposal could be just a question" ?


> Il giorno 30/gen/2015, alle ore 21:26, Pietro Speroni <notifications@github.com> ha scritto:
> 
> each proposal could be just a question

**Comment by pietrosperoni** [comment]
corrected, @giovanisp

**Comment by giovanisp** [comment]
Yes. The triangle could be agree/oppose/don't know? Not sure how your math works with images.

**Comment by pietrosperoni** [comment]
It's simpler. People have to just vote on a 1D continuum agree/disagree (but also the words might change: like/dislike might fit better). If there is no "I do not understand" everything becomes much easier.

In any case, for now, just being able to upload an image would be enough

**Comment by giovanisp** [comment]
it's there. Images+text  proposals was added as a new issue.
