### ISSUE TITLE
New proposal fields not being reset allowing duplicate proposals being submitted

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#165]
I was writing several proposals through the iPad for a question in Vilfredo.org . Then on the last proposal I did not write a title. I simply forgot. But instead of throwing me an error, it copied the same title I sent from my previous proposal. There is probably a variable that needs to be restarted.

**Comment by derekpa** [comment]
Not related to ipad. A general bug.
