### ISSUE TITLE
I just voted and can move the question to results page without waiting for the other participants

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#171]
![image](https://cloud.githubusercontent.com/assets/180794/6059100/273dada4-ad2e-11e4-986c-a4d06cabb0c6.png)

I just voted, and I can move to results only with my votes in it. i know it is going to be replaced by the "end", but anyway the system needs more information about the "health" of a given question (ie.: how much engagement is going on and if the discussion is heating or cooling down - maybe based on comments for/against and questions/answers on proposals as well). See also #166

**Comment by pietrosperoni** [comment]
This is all part on how the qeustion will move on. It is a long discussion and something that I am eager to do when we meet in Italy. Can you keep it on hold in the meantime?

**Comment by giovanisp** [comment]
sure.

**Comment by derekpa** [comment]
No, if this still happens then it is a bug that needs fixing now. It should appar once at least two people have voted.
