### ISSUE TITLE
changes on home screen

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#174]
Please consider the following small changes in the home screen:

![image](https://cloud.githubusercontent.com/assets/180794/6059721/3ad6da82-ad35-11e4-9852-f29e66d41d41.png)

Relates to #139

**Comment by giovanisp** [comment]
do you think we can have it by this release @derekpa ?

**Comment by giovanisp** [comment]
Also, let's get rid of the rounded borders for the colored boxes.

**Comment by derekpa** [comment]
Not now, no.

**Comment by giovanisp** [comment]
hard ?

**Comment by giovanisp** [comment]
anyway there is another issue for that.

**Comment by derekpa** [comment]
Too many  other things to do.

**Comment by derekpa** [comment]
I'll add the invitations received next release. Not messing around with DB migrations and lots of css stuff at this late date. No time now.

**Comment by pietrosperoni** [comment]
I agree. Definitely neither important nor urgent. IF we need to make those changes let's wait until after the UX design and the UI design.
Instead the (invitation accepted refused) is important, but can wait until next release.

**Comment by giovanisp** [comment]
Ok for invitation. We can use bootstrap span attributes "label-success" and "label-danger" to create the accept/reject buttons. Also, those proposals created directly by the current user, they go directly under the "Propose an answer to a question" panel:

![image](https://cloud.githubusercontent.com/assets/180794/6486641/927f8c54-c28c-11e4-8c15-5066e5ab2605.png)

**Comment by giovanisp** [comment]
re #191

**Comment by derekpa** [comment]
Actually, re #191, we're not currently giving the invited user the chance to see the question before accepting or rejecting, merely the chance to view the title and author. So either we pop up a modal or permit to go to the question page in read only mode

**Comment by giovanisp** [comment]
Why can't them simply click on the invitation and join the question if they accept, avoid the question if they reject the invitation? In case the user is not registered, they are first redirected to the registration page along with the invitation token that will allow them to go through the registration process and auto login, performing the previous operation (accept/reject). if they are registered but logged out, they are redirected to the login page and once logged in the system also performs the operation chosen (accept/reject).

**Comment by derekpa** [comment]
> Why can't them simply click on the invitation and join the question if they accept, avoid the question if they reject the invitation?

Sorry @giovanisp, could you make that clearer? You mean keep it as it is, without reading the text of the actual question?

**Comment by giovanisp** [comment]
I think that it is good as it is, but - as you said - we need to make the question text link take the user to the question in readonly mode until he accepts/rejects the invitation (following the above flow).
we can also add Accept/Reject buttons in the same place we are now positioning "move to...." Buttons with a blue info box "You have been invited to this question. Why not help now?"

**Comment by giovanisp** [comment]
I did not meant using a modal (again...) but using the question page and the buttons "accept/reject" in the place where actually we find "submit proposal" "move to voting"...  But I created another issue for that  #311.
