### ISSUE TITLE
Links in a question text should be clickable

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#176]
Right now they are not:
![screen shot 2015-02-05 at 15 32 48](https://cloud.githubusercontent.com/assets/1333674/6062945/8de358ac-ad4b-11e4-9f52-4adbc1e51501.png)

**Comment by giovanisp** [comment]
Really?
we said we wanted no links in the proposal text, otherwise people would be encouraged to post external material.
also, we talked about having a ASIDE bar for reference material, so users could diligently add links. Or... Not?

**Comment by pietrosperoni** [comment]
Hmm, good point. I needed the link to post some pictures. Also a link to google map.

Let's say that for sure links on the question it should be clickable.

For the proposal, I wonder if we could white list a number of websites, like maps.google, wikipedia that can be used as reference bibliography.

**Comment by giovanisp** [comment]
I propose allowing links in the questions. If more than "X" links are found (parameter on client config file), we show a captcha to block spam robots.

On links in proposals, I opened #179

**Comment by pietrosperoni** [comment]
Yes, I agree
