### ISSUE TITLE
Possibility to edit a question before anyone else started writing proposals

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#178]

**Comment by giovanisp** [comment]
How do you know if someone is already writing a proposal until they submit it ?
I propose a specific lapse of time ("X" minutes, a parameter in client config file, default "3") on which the author can make changes and those remain tracked as they are like on Facebook.

**Comment by giovanisp** [comment]
I see you posted this as rc2.
We can allow full edit for now until submission of first proposal, but then commit to enhance this as above. Or postpone the feature altogether.

**Comment by pietrosperoni** [comment]
Yes, edit until submission of first proposal

**Comment by pietrosperoni** [comment]
Ok, it works, but I would say the edit box should (also) be inside the question page. And not just in the general index page. And very big, like the Submit new proposal, Button.

**Comment by pietrosperoni** [comment]
Thanks @giovanisp
