### ISSUE TITLE
tooltip in home page proposals in voting phase needs to show number of voters

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#181]
In this area (voting) the tooltip must show the number of users that already voted at least 1 proposal (or if all users voted all proposals), so it can move next and everyone can have a visual hint of the voting progress.
![image](https://cloud.githubusercontent.com/assets/180794/6078427/be5953c6-adf8-11e4-92ea-16405c89d027.png)

**Comment by pietrosperoni** [comment]
and number of invited participants who has accepted

**Comment by giovanisp** [comment]
That goes in the green box. See the issue on redesign... 


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 06/02/2015  12:57  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] tooltip in home page proposals in voting phase needs to show number of voters (#181) 
 
and number of invited participants who has accepted

**Comment by pietrosperoni** [comment]
Not so fast, it is not very clear what it says. I put it on hold for a couple of days.

**Comment by giovanisp** [comment]
Ok,  let's change the phrase to 

"X out of Y participants submitted N proposals"
