### ISSUE TITLE
invert question icons on home page

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#183]
The green and blue icons are inverted. 
![image](https://cloud.githubusercontent.com/assets/180794/6081122/64ccc7a6-ae17-11e4-98a5-f5fa6a907861.png)

**Comment by derekpa** [comment]
Not rally a bug. I just picked those colours pretty much at random. 

Would it look better to change them? If anything I would consider changing the red to better contrast with the background.  There are sites where you can find the best contrasting colours.

**Comment by giovanisp** [comment]
> There are sites where you can find the best contrasting colours.

Funny. I used one of those! :-p

Yes,Dark green icon on light green background, and dark blue icon on light blue background.

We will hopefully change the user dashboard later with a much better UX (I have it in mind but needs much manual work to mockup).

**Comment by giovanisp** [comment]
Is that on test  @derekpa ?

**Comment by derekpa** [comment]
Yes. Don't you see it? Remember you have to reload the page....
