### ISSUE TITLE
user can move his vote inside the results triangle

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#186]
when in voting phase, when the user sees the results triangle, he cannot move his vote. He should be able t move his vote and see the connection line. This has to work only after 3 or more people have voted.

**Comment by pietrosperoni** [comment]
This is a small work (I hope) which will give a big result in terms of usability experience

**Comment by giovanisp** [comment]
was that 2.0.0-rc2 @pietrosperoni  ?

**Comment by pietrosperoni** [comment]
I forgot, but yes it was. Only we did not assign it to @derekpa . I will do now, but I don't think he can make it for this release

**Comment by derekpa** [comment]
Why 3 or more, and not 2 or more?

**Comment by giovanisp** [comment]
That was before we talked about the one-user voting use case. The user should be able to move his vote and see the effects in the resulting points connected.

**Comment by pietrosperoni** [comment]
Ok ignore the only after 3 or more. Let it function immediately even with a single person. We need to make some tests to see how it comes out.

**Comment by pietrosperoni** [comment]
In fact I would suggest to have this depend upon an external constant x, that describes how many people need to have completed voting before you can see the results. Eventually x might depend on the question, some questions have a different x than others. But for now we need to be able to try and see how it comes out.

**Comment by pietrosperoni** [comment]
by the way, I think this might be the biggest upgrade in terms of usability on this release. i am really looking forward for this. :-)

**Comment by derekpa** [comment]
> That was before we talked about the one-user voting use case. The user should be able to move his vote and see the effects in the resulting points connected.

Yes, but for that you only need 2, not 3. I was wondering where the 3 came from.

**Comment by pietrosperoni** [comment]
I said 3 because taking the median, the votes become stable when you have at least 3 people voting. In this way people would not vote to the extremes just to move the vote in one direction or the other. In fact it might be that is good to permit this with a single person, with 3 (or more) persons, but not with 2 persons.

**Comment by giovanisp** [comment]
>In fact I would suggest to have this depend upon an external constant x, that describes how many people need to have completed voting before you can see the results. Eventually x might depend on the question, some questions have a different x than others. But for now we need to be able to try and see how it comes out.


Yes, let's make this a parameter, default to 1 as of now. This gives us some room for future improvements.

**Comment by derekpa** [comment]
Anyone have any sound reasons why we would show a user's votes and the median when the triangle shows the results of just one user?

**Comment by pietrosperoni** [comment]
Hi @derekpa , I don't understand the question. 
In the results triangle you show the medians of all the votes on all the proposals, not just the user votes of one.

**Comment by derekpa** [comment]
I'm talking about when there is only ONE lone participant.

**Comment by pietrosperoni** [comment]
Good point. So maybe when there is only one lonely voter we should just show his votes, with a warning.

**Comment by derekpa** [comment]
A warning?

**Comment by pietrosperoni** [comment]
yes, better than a warming.
Just to let him know that right now no one else has voted.
