### ISSUE TITLE
add simple multi-generation button

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#187]
the user that has created the question will have an action button next to "move to results" that says "move to next generation", this is the first step for the advanced multi-generation that will in the future be handled by Vilfredo.

**Comment by pietrosperoni** [comment]
As it is manual, we don't even need to check if there is a consensus. The person asking the question simply can decide if (S)He is satisfied with the result or not.

**Comment by giovanisp** [comment]
See #260 mockups for where to add the "Move to next generation" button. (In the space visible only to author)

**Comment by giovanisp** [comment]
I can't, missing button:

![image](https://cloud.githubusercontent.com/assets/180794/6668906/5309baea-cbf6-11e4-84f6-f917e7ea97f6.png)

**Comment by giovanisp** [comment]
See #260 mockups for where to add the "Move to next generation" button. (In the space visible only to author)

**Comment by giovanisp** [comment]
the comment above is related to #261
