### ISSUE TITLE
implement question settings page

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#188]
in this page the user will see the current settings before starting a question (at the moment only if the question is text or if it is photo)

**Comment by pietrosperoni** [comment]
This will become really important. And it will have several layers. Some simple decisions, and then more and more complex as the user is more experienced. But, as Giovani said, now it is only if the question is "text" or "photo"

**Comment by giovanisp** [comment]
can be prettier....
