### ISSUE TITLE
show pareto front color in the results triangle

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#189]
need to assign the pareto front colors to the actual gray points in the result triangle.

**Comment by pietrosperoni** [comment]
Proposals in the Pareto Front should be brightly colored. While the others should be greyed.

**Comment by pietrosperoni** [comment]
No, it does not work.

I went to question 4 on the test page: http://test.vilfredo.org/question/4
and changed my vote for proposal Fair Democracy. Voting against it. As a result now the Pareto front had 6 elements dominating everything else and two other proposals.
Instead in the triangle you can only see 4 proposals. Not in particular that proposal 12 is in the Pareto Front below but it is shown as not in the Pareto front on the Triangle.

![screen shot 2015-05-08 at 17 20 57](https://cloud.githubusercontent.com/assets/1333674/7540521/4606bb5c-f5a6-11e4-8538-3c5586679ec8.png)
![screen shot 2015-05-08 at 17 21 31](https://cloud.githubusercontent.com/assets/1333674/7540522/4621f8ae-f5a6-11e4-8ac0-ad32a057ea2f.png)

**Comment by giovanisp** [comment]
closing. enhancements go to 2.1 @pietrosperoni

**Comment by pietrosperoni** [comment]
Sorry, but this was one of the key things for 2.0.0. Let me see the review and decide if this is to be closed or not

**Comment by derekpa** [comment]
This was working for me. Has no-one tested it yet?

**Comment by pietrosperoni** [comment]
Let me test this again

**Comment by pietrosperoni** [comment]
Yes, it works, sorry.

**Comment by giovanisp** [comment]
Too much work for Pietro :-)
