### ISSUE TITLE
user can explicitly reject an invitation

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#191]
so far when the user receives the invitation link, if they click they are automatically added to the question.
Instead they should be given the opportunity to see what the question is and explicitly reject the invitation. If they don't do any action (reject or accept) the invitation will keep valid until it expires (to be implemented later).

**Comment by pietrosperoni** [comment]
Also once a person rejects an invitation, the person inviting him should be alerted.
"asocial person ... decided he would rather not discuss this with you because he hates you" sounds like a good possible email ;-)

**Comment by giovanisp** [comment]
See mockup on #174 in the final comments

**Comment by derekpa** [comment]
I think I said it somewhere else, but at the moment we do not show the user the question text, only the title and author. We should probably show the full question text (in a modal) before the user accepts or rejects.

**Comment by giovanisp** [comment]
Yes. If the user clicks on the question, instead of doing nothing it can open a modal with the full text and repeat both "Accept / Reject" buttons at the bottom. Once clicked, the home dashboard refreshes with the new state.

**Comment by pietrosperoni** [comment]
![screen shot 2015-04-02 at 13 42 47](https://cloud.githubusercontent.com/assets/1333674/6964096/f78100de-d93d-11e4-8b78-bcd4cd374a7d.png)
