### ISSUE TITLE
use gravatar for user photos

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#193]
use gravatars related to which user emails are linked to his account. The default account email will use the gravatar photo to show on the top profile.

**Comment by giovanisp** [comment]
relates to #192

**Comment by pietrosperoni** [comment]
Ok, but it should not use the default email address. Instead it should let a user decide which of his emails to use. And this should be decided in the profile page #192

**Comment by derekpa** [comment]
This is a duplicate of issue #34 for release 2.4. You should close this.
