### ISSUE TITLE
HORRENDOUS BUUUUG: that deletes all the content

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#209]
If you write a proposal on vilfredo.org that is more than 1000 chracters it will say that proposal content must be less than 1000 character. But the content should be less than 10000 (10 thousands) characters, not 1 thousand. First error. Second if the edit box active when you click on submit is the abstract then not only does it not accept the proposal, but it also DELETES everything. Aaaargh! Please fix this super urgently before we are lynched.

The movie will soon be available here: https://www.dropbox.com/s/v2m17mmkr6vfebn/Google%20Chrome%20-%20Vilfredo%20-%20Fair%20Decision-Making.mov?dl=0 for some time at least.

**Comment by derekpa** [comment]
OK, the first problem, which I've fixed on the live site, is that I had forgotten to update core with the new valid text lengths. They now match the values set on the client.

I'll look at the second problem.

**Comment by pietrosperoni** [comment]
No, the proposal wasn't created. In fact I could not find a way to upload such a long proposal at all. Not writing the abstract and not, without writing the abstract.

Pietro

**Comment by pietrosperoni** [comment]
tested on the live site. And it works. @derekpa , remember to upload the changes also to the test, nightly, and demo site.
