### ISSUE TITLE
Prevent modals from closing if user clicks on background

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#211]

**Comment by pietrosperoni** [comment]
i thought that was a feature

**Comment by derekpa** [comment]
Not, I think, if you've spent an hour writing a proposal :-)

**Comment by giovanisp** [comment]
If the modals hava their own close buttons, it is a bug.
Anyway in the future I'd like to have the most part of the application out of modals, and in pretty urls like https://vilfredo.org/q/create  (creates a new question)
https://vilfredo.org/q/my-first-question-is-here/    (SEO friendly question page)
https://vilfredo.org/q/my-first-question-is-here/p/create  (create a new proposal for that question)

**Comment by pietrosperoni** [comment]
Why are we speaking about SEO of questions if questions are not publicly visible?

And yes, it was a bug. I did not understand that it was during the writing phase.

**Comment by giovanisp** [comment]
> Why are we speaking about SEO of questions if questions are not publicly visible?

They are human-friendly, and in the future we will be ready for SEO if questions will be made public (instead of converting a bunch of numbers)...

**Comment by pietrosperoni** [comment]
what about after a question is closed, it might become public (for some questions)

**Comment by giovanisp** [comment]
Open a new issue about that...

Inviato da iPad

**Comment by giovanisp** [comment]
This issue is closed. Pretty URL's are a new issue at #244 . @pietrosperoni open a new issue for your comment
> what about after a question is closed, it might become public (for some questions)
