### ISSUE TITLE
pop up saying this is still being tested

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#212]
I am testing a software called AffinityPhoto. When you open it it shows this image:
![screen shot 2015-02-10 at 12 33 42](https://cloud.githubusercontent.com/assets/1333674/6126380/681cc544-b120-11e4-8a90-c05e81670c2d.png)

We should have something similar for Vilfredo

**Comment by giovanisp** [comment]
we are not calling ourselves "beta".
Adding interruptions might slow down registrations.
