### ISSUE TITLE
12 characters is not enough for secure password

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#216]
12 seems arbitrarily short.
![screen shot 2015-02-11 at 22 07 47](https://cloud.githubusercontent.com/assets/1789426/6157612/b13338ce-b23a-11e4-839e-3f9a69d415d7.png)

**Comment by pietrosperoni** [comment]
Indeed. Why 12 @derekpa . Can we put this to 40 at least?
@giovanisp what you think? What is the standard in the PA?

**Comment by giovanisp** [comment]
Surely we need to allow longer passwords.
I regularly see fields asking a minimum of 8 chars and the max varies from 20 to 40 until ... no max (that is... 255 in varchar). I would lave it at 255, since some people use hashes AS their password and we save passwords salted and hashed/encrypted.

**Comment by derekpa** [comment]
Yes, it was an error.

**Comment by giovanisp** [comment]
Ok. Let's try at 60 chars.
