### ISSUE TITLE
Abstract should be closed

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#218]
* I think since the abstract is optional it should be below the text. 
* Also it should be indicated somehow differently in order to show it's optional. Maybe ligther grey around the whole field?

![screen shot 2015-02-11 at 22 12 21](https://cloud.githubusercontent.com/assets/1789426/6157726/98caffc8-b23b-11e4-8386-10bf3576e0c6.png)

* Also I think the submit button should be at the left hand side of the dialog. (The more logical convention, see for example github)

**Comment by pietrosperoni** [comment]
The whole writing page will need to be redesigned. But in particular no, I disagree. The abstract should not be below the text. Often people do not complete those forms in order, and write the title at the end, for example. Maybe the abstract should remain closed, and open if the proposal text is too long.

**Comment by vvorski** [comment]
The abstract confimused me. I naturally wrote there and it didn't allow me to submit, had to cut and past my text.

Closed by default is best idea I think.

V/.

**Comment by pietrosperoni** [comment]
Ok so the abstract should be closed, and then only open if the proposal is too long.

**Comment by giovanisp** [comment]
>Also it should be indicated somehow differently in order to show it's optional. 

We need to use the "*" convention for mandatory fields. At least until we have this modal box redesigned as a page  http://vilfredo.org/q/my-question-here/p/create

>Also I think the submit button should be at the left hand side of the dialog. (The more logical convention, see for example github)

Agree.

**Comment by giovanisp** [comment]
Missing:
> Ok so the abstract should be closed, and then only open if the proposal is too long.
>We need to use the "*" convention for mandatory fields. At least until we have this modal box redesigned as a page http://vilfredo.org/q/my-question-here/p/create
>Also I think the submit button should be at the left hand side of the dialog. (The more logical convention, see for example github)

**Comment by giovanisp** [comment]
ok...  no * for mandatory fields.... we will deal with it globally later on.
