### ISSUE TITLE
For small texts do not need scroll bar.

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#219]
This is spurious:
![screen shot 2015-02-11 at 22 22 30](https://cloud.githubusercontent.com/assets/1789426/6157824/9217c214-b23c-11e4-840b-3bcf9df91fee.png)

**Comment by pietrosperoni** [comment]
@giovanisp , please decide the milestone :-)

**Comment by giovanisp** [comment]
small UI fixes to do @derekpa.

**Comment by derekpa** [comment]
Overflow set to auto. Only happens sometimes on chrome. Not worth wasting time on something as minor as this this at the moment.
