### ISSUE TITLE
Chrome does not remember vilfredo login

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#221]
For all other sites chrome pops-up suggestion to remember the password on login, but not for vilfredo this is highly inconvenient.

Same behaviour in safari.

**Comment by pietrosperoni** [comment]
You are right. @giovanisp do you know why? Is it because we use so many pop-ups?

**Comment by pietrosperoni** [comment]
but it's an enhancement, com'on, not a bug ;-)

**Comment by vvorski** [comment]
It's a bug. It's standard functionality all sites Support and users expect.

I have per site random passwords so this forces me to cut and paste the password from my password manager every time. Not nice...

V/.

**Comment by pietrosperoni** [comment]
but more secure, like a bank. It's a feature!

**Comment by vvorski** [comment]
I am starting a consumer rights movement to fight "features" like that...

V/.

**Comment by pietrosperoni** [comment]
:+1:

**Comment by giovanisp** [comment]
@derekpa the form seems to have autocomplete="on" 
Is knowckout.js ruining something ? Like that... http://rlaanemets.com/post/show/autofill-troubles-two-way-binding-frameworks , http://stackoverflow.com/questions/14537199/knockout-js-doesnt-pick-up-autocompleted-or-prefilled-values , .... ?

**Comment by giovanisp** [comment]
works on test.vilfredo.org for me. Chrome 41.0.2272.89 m
