### ISSUE TITLE
The index page should say in the tooltip how many people have voted

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#222]
![screen shot 2015-02-12 at 16 34 51](https://cloud.githubusercontent.com/assets/1333674/6170362/5d6041ca-b2d4-11e4-9525-c6ec1600f4a3.png)

**Comment by derekpa** [comment]
![screen shot 2015-02-26 at 13 01 54](https://cloud.githubusercontent.com/assets/1368533/6392354/bc092316-bdb7-11e4-9b0c-e5cb32245da7.png)

**Comment by giovanisp** [comment]
Can we add an "if" so if all users have done the action it says "all users"?
Also,ccan we start the phrase with the number, it is shorter "3 out of 5 participants voted" is clearer IMHO.

Inviato da iPad

**Comment by derekpa** [comment]
Pietro asked if we could show: total participants, how many have started to vote, how many finished. So possibly just something like:

Total participants to vote: 7
Not Yet Voted: 1  Voting: 2   Finished: 4

**Comment by giovanisp** [comment]
too long. We still do not have the button for the user to say "I finished voting" do we ?   If we don't,  @pietrosperoni has to create a new feature issue for this and I'd say that we stick with a simpler and shorter 1-line phrase like the one above: "3 out of 5 participants voted"  that we can change when we have the action that allows users to inform Vilfredo they have finished proposing or voting.

**Comment by pietrosperoni** [comment]
hmm, we have 3 numbers, and we need to show them all. How many finished, how many are doing it, and how many have not yet started. I vote for @derekpa version

**Comment by giovanisp** [comment]
do we *actually have* the 3 numbers?  Is there a button for the user to say "I finished voting" ?

**Comment by pietrosperoni** [comment]
Not know. We will have buttons so that people can say if they will change their vote later or not. But so far you have people who have voted on all proposals, people who have voted on some proposals, and people who have not voted on any proposal. So those are 3 numbers. And their sum is the total number of people invited to vote. As Derek presented you see all 4 numbers nicely presented :-)

**Comment by giovanisp** [comment]
Ok, 3 numbers considering that a user who has "finished" is one that has read and voted all proposals, which won't be the case in the future. 
Anyway, the way the phrase is presented is too long for a tooltip. I'd propose:

"Out of 6 participants, 3 finished voting and 1 started voting."

Which implicitly means the other 2 did not started voting. Also, let's consider 

"No one started voting. Be the first!" 

when no one started voting. And naturally the partial cases easily derived from the full phrase:

"Out of 6 participants, 3 finished voting"
"Out of 6 participants, 1 started voting"

Finally the full case:

"Great! All participants have voted."

**Comment by pietrosperoni** [comment]
yes, good one

**Comment by giovanisp** [comment]
Missing:
> Also, let's consider
"No one started voting. Be the first!"
when no one started voting. 
Finally the full case:
"Great! All participants have voted."

![image](https://cloud.githubusercontent.com/assets/180794/6468290/6482340e-c1d4-11e4-9063-d60fbfa98f5c.jpg)
![image](https://cloud.githubusercontent.com/assets/180794/6468291/64af2b76-c1d4-11e4-8ef8-10761211a34c.jpg)

**Comment by derekpa** [comment]
OK, does it really make any sense to say "Great! All participants have voted" and display th goto results button when there is only 1 participant, ie just 1 person writing and voting?

**Comment by pietrosperoni** [comment]
We need to decide if it makes sense to have a single participant. If it does then it could be used to order a set of proposals. Maybe n people suggest ideas, and then a person thinks them through, and votes them. Or maybe a teacher evaluates the essays of some students and Vilfredo orders them. Then the students would be the people proposing and the teacher the person voting. If this is acceptable then yes it makes sense. If we do not permit that, then a question with a single person who is allowed to vote cannot even start.

**Comment by derekpa** [comment]
> If we do not permit that, then a question with a single person who is allowed to vote cannot even start.
Precisely. I think it does make sense to allow one person voting, if like you suggest there are others writing proposals. 

But what about the cases we have now, where Giovani is writing his proposals then voting on them?

It does make sense if we see people using Vilfredo to think through a problem and order a set of possible solutions he thinks up himself.

**Comment by giovanisp** [comment]
I think this is also a valid use case. However we will always show the warning messages as in the mockups in #260 (let's do that first).

**Comment by derekpa** [comment]
What do you mean " always show the warning messages "?

**Comment by giovanisp** [comment]
In the sense that it will keep showing the lonely user the message "Why not invite others?" "The more proposals the better"... In short it does not change anything, just the new message (see my last comment on #260)

**Comment by giovanisp** [comment]
Missing:
>"No proposals so far. Be the first!"
>"No one started voting. Be the first!"
>"Great! All participants are done proposing."  (when all click the button in #190 
>"Great! All participants have voted."

**Comment by giovanisp** [comment]
see the previous comment... cases are still missing the proper wording:

![image](https://cloud.githubusercontent.com/assets/180794/7540611/656f6dbe-f5af-11e4-978e-d21a9ec7ac0c.png)


remember to apply the wording to the other boxes as well (proposals and ended questions)...

**Comment by derekpa** [comment]
I did. Could you be more specific?

**Comment by giovanisp** [comment]
Phrases in the comment above and in the image do not match exactly. Or is it my cache?

**Comment by derekpa** [comment]
![screen shot 2015-05-14 at 10 16 30](https://cloud.githubusercontent.com/assets/1368533/7629167/74385460-fa22-11e4-83cb-29287ba28eff.png)
![screen shot 2015-05-14 at 10 16 46](https://cloud.githubusercontent.com/assets/1368533/7629168/743d1a36-fa22-11e4-9bc4-533cb06565b3.png)

**Comment by giovanisp** [comment]
@derekpa   in the voting panel replace "Out of x participants no one started voting. Be the first"  with only  "No one started voting. Be the first!". 

It is shorter, the important message there is that no one started voting. We should avoid long phrases. People tend not to read a lot.
