### ISSUE TITLE
Bug on firefox, probably cache

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#223]
My father using firefox on vilfredo.org says how after he logs in, he sees 4 questions. Two of them he can open, while 2 others when he tries to open them, will rapidly show him a message that he is not allowed to participate. And then the system reloads the homepage.  
He tried logging out and logging in again but it does not change.  
He tried on Safari and in that case everything works well.

Probably there is a problem with the cookies and some cache. But it is quite difficult for the average user to be told that they need to clear the cache. 

@giovanisp I assign this to you, as I don't know if it is worth trying to solve it at all or not. And in case which milestone

**Comment by giovanisp** [comment]
To know if it was a cache issue... Clearing the cache did it work now?

**Comment by pietrosperoni** [comment]
How do we explain to users,  especially not the technical ones, how to clear the cache?

**Comment by giovanisp** [comment]
How can you be sure that there is a cache problem? Was that a cache problem? In the sense that ot worked after clearing cache? Did it happen in vilfredo.org or test or nightly? Keep in mind test and nightly are unstable environments. When opening a bug now we need to start adding some more context information, to replicate them.

**Comment by pietrosperoni** [comment]
I am not sure it is a cache problem. I asked my father to clear his cache and tell me if anything changes. I sent him this link:
 https://support.mozilla.org/en-US/kb/how-clear-firefox-cache?redirectlocale=en-US&redirectslug=How+to+clear+the+cache

**Comment by giovanisp** [comment]
Ok. Of course users do not need to learn ho to clear cache to use our app ! If it is a cache problem, let's fix ;-)

**Comment by pietrosperoni** [comment]
Ok, my father cleaned the cache and reports that now it works.
@giovanisp what is the standard thing to do in those cases? We cannot educate the whole world to clean the cache often if they want to use our program :-(

**Comment by giovanisp** [comment]
The standard thing to do is to replicate the bug.
please write down all the steps to replicate the problem, so we track it down and fix it.
Obviously there is no need of cleaning cache to use Vilfredo everytime. If it is needed, it is a bug. Let us know also the browser version and any other useful information (data entered, etc...).
Gs

Inviato da iPad

**Comment by derekpa** [comment]
Dos not sound like a cache problem.

**Comment by derekpa** [comment]
OK so he was using the LIVE site...

**Comment by pietrosperoni** [comment]
I don't think we are able to reproduce the bug. We'll see if this happens. In the meantime, closing it
