### ISSUE TITLE
Move to results button appearing immediately - before voting.

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#228]

**Comment by derekpa** [comment]
Now should only appar once at least 2 people have finished voiting

**Comment by pietrosperoni** [comment]
I am not sure we shouldn't let people just vote alone. Sounds weird but it could be a nice way for people to order proposals. The only thing is that if we invited x people to vote, and y people completed voting, an alert should appear saying: are you sure you want to go to results? Those people:... have not completed voting.

What do you think @derekpa ?

**Comment by giovanisp** [comment]
@pietrosperoni please make this a new issue...
