### ISSUE TITLE
fast link to the demo site for people who want to just test the system

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#229]
We should re-address people who just want to test the system to go to the demo site.

This should happen through a link on the registration page, something along the lines:
if you just want to test the system, please do so on the demo site: demo.vilfredo.org. Then when you are ready come back here and register here.

In fact we should even slow done the possibility of registration. Where people "ask" to be registered with their username and email address, and we let them in, few at a time. In this way we raise the attention, and keep the username space clean of bots

@giovanisp your thoughts, before this goes to @derekpa ?

**Comment by giovanisp** [comment]
Good point. 
We can use only the invitation system for the live site, so people register if they have a token.

Ps.: are you mentioning bots because we have them on live site?

**Comment by pietrosperoni** [comment]
at the moment there are no bots I am aware off.

Ok, pass this on to @derekpa

**Comment by giovanisp** [comment]
Are we going to do this *before* the new invitation system ?  
If so, it should be a CONFIG parameter

REGISTER_INVITATION_ONLY = true

So the system can work for those who download in either way (invitation-only or open for registrations).

**Comment by pietrosperoni** [comment]
Yes. Assigning it to @derekpa

**Comment by giovanisp** [comment]
ok @derekpa  see the config in the above comment. Demo is setup as open for registrations while vilfredo.org as invite-only.

**Comment by derekpa** [comment]
OK, I copied the issue over to core #63 because its core issue. Its on test, which I've currently set to invitation only.

**Comment by derekpa** [comment]
![screen shot 2015-03-07 at 20 50 46](https://cloud.githubusercontent.com/assets/1368533/6543217/e22aac80-c50b-11e4-8f87-903efd11fc7c.png)

**Comment by giovanisp** [comment]
ok I fixed the link. DEMO will be always open for registrations.  

TEST and LIVE are invitation-only.

**Comment by derekpa** [comment]
@giovanisp Yes, the link should pint to demo not test.
But remember LIVE will not be invitation-only until next release - or unless we add the code as a hot fix.

**Comment by giovanisp** [comment]
Understood.
For now test can be invitation-only. Nightly could be open for registration.

Inviato da iPad

**Comment by giovanisp** [comment]
Can we move the message to the main screen (above the gray jumbotron) and remove the Register button ? Message could be like:

"Registration on this site is by invitation only! 
If you wish to test Vilfredo you can register at the Vilfredo Demo site."

As of now the user has to try registration to know he can't register... It is better that the functionality is removed altogether. When invited, the user can compile his information.

**Comment by pietrosperoni** [comment]
@giovanisp , if it is clear, then assign @derekpa to code it :-)

**Comment by giovanisp** [comment]
relates to fairdemocracy/vilfredo-core#63
