### ISSUE TITLE
Answer to questions box broken. Looses the text when too long

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#233]
Bloody Murderer!

I was writing an answer to a question/enquiry/doubt inside a proposal. I wrote more than 300 characters. When I clicked save it  told me I should write only 300 characters, AND DELETED ALL I HAVE WROTE.

1) 300 characters for the answer is too short (at least 500, better yet 1000. It is an answer to a specific question, who is not interested does not need to read it)
2) it Must let me know the limits before hand
3) It must let me know how many chrachters I have written
4) if I am beyond the limits the button should be greyed, or be a (save draft).
5) In no case should the text that I wrote be lost

**Comment by giovanisp** [comment]
Add a "read more..." Ajax link after the first 300 chars more or less, so the actual 2 column ui does not get broken. This modal box sould be in the future substituted by a plain url template https://vilfredo.org/q/my-question/clarifications

Each clarification would have a hidden url for internal ajax calls, not accessible directly like https://vilfredo.org/q/my-question/c/edfgsgd243527sgfdtbs 

Inviato da iPad

**Comment by giovanisp** [comment]
is this fixed ?  back to @pietrosperoni  ?

**Comment by pietrosperoni** [comment]
It does not delete the text anymore. But it also does not tell me how many characters do I need to delete. SHould we open another issue for this @giovanisp ?

**Comment by derekpa** [comment]
No. Not finished with this yet. Thats why its not tagged for review.

**Comment by pietrosperoni** [comment]
![screen shot 2015-02-27 at 19 08 49](https://cloud.githubusercontent.com/assets/1333674/6418268/1178c9da-beb4-11e4-998d-71050f5c512c.png)
The problem is in the answer, not in the question :-)

**Comment by derekpa** [comment]
I'd thought th question was done too. They all should have char counts now. Nver tested for answers though.

**Comment by derekpa** [comment]
It should appear when you click on the answer box

**Comment by pietrosperoni** [comment]
It doesn't. I am on Chrome. Instead it appears on the question box.
It's not a problem of cache as it did not even appear on the question box before, so it is obviously using new code.

**Comment by pietrosperoni** [comment]
I did say the problem was on the answer. Also please can you let answers be longer than 300. Question can be 1000 characters, let also answers be the same.

**Comment by derekpa** [comment]
On CHROME... (it probably IS a ache problem). And the lengths ARE 1000!

![screen shot 2015-02-28 at 12 54 52](https://cloud.githubusercontent.com/assets/1368533/6426247/0daf0342-bf49-11e4-9578-47891372591e.png)

**Comment by pietrosperoni** [comment]
It still says 300 above (even though it is now 1000).


![screen shot 2015-02-28 at 15 03 00](https://cloud.githubusercontent.com/assets/1333674/6426434/e81b7590-bf5a-11e4-9de3-07230c78151f.png)

When you delete some text it writes a very confusing message:

![screen shot 2015-02-28 at 15 03 53](https://cloud.githubusercontent.com/assets/1333674/6426438/1a650228-bf5b-11e4-8e6d-b8ff622d7983.png)

And I cannot delete stuff to get the message accepted.

Also when a message is too long instead of just making the edit box a bit bigger it opens another modal, the modal of the modal.

So there definitely are 4 bugs inside:
1) deleting the characters should give the right number deleting the previous number
2) deleting the characters should let you submit when you go under 1000
3) it should not say 300 but 1000
4) if the answer is bigger the edit box should adapt to it.

**Comment by pietrosperoni** [comment]
And 
5) the text gets written outside of the edit box, as in the image above.

**Comment by pietrosperoni** [comment]
(sorry)

**Comment by derekpa** [comment]
How is it now?

**Comment by pietrosperoni** [comment]
Now the answer button (the one to submit) does not work. LOL
(but the counting seems ok)

**Comment by derekpa** [comment]
so why does it work on my browsrs?

**Comment by derekpa** [comment]
Do you understand how to check for javascript errors on chrome?

**Comment by pietrosperoni** [comment]
hmm, nop. Sorry. @giovanisp can you check this too please.

**Comment by pietrosperoni** [comment]
Ok, just retested it and now it works. Not sure what changed between yesterday evening and now. Probably a cache problem that kept part of the old code and part of the new one.
