### ISSUE TITLE
move the cookie advise from the footer to above

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#234]
I just invited someone. definitely a hacker, very expert with security systems. But he was stuck by the "we use cookies" message. He also did not realise he had to click on OK. He is NOT colorblind (there goes my theory), but he said:

I would NEVER consider that the footer holds a button to something that I NEED to do.

So I would suggest that we move the message from the footer to either above or the center page, as a big modal window that @giovanisp love so much. And that can only be closed by clicking on: ok use the cookies.

@giovanisp your thoughts before we move this to production

**Comment by giovanisp** [comment]
Place the actual cookie bar on top of the screen. in fact he is right, very few sites have it at the bottom e most do not enforce the agreement (we enforce in the sense that we do not allow registration... We are very "fair with the law")  :-p
The message could be tweaked to say "must accept cookies"... 

Inviato da iPad

**Comment by giovanisp** [comment]
BTW ask him if he has some penetration test security sw he could run against vilfredo and tell us some securit holes :-) I know there are many like AppScan ... If he can help us on that front it would be very nice.

Inviato da iPad

**Comment by pietrosperoni** [comment]
Do you want that we ask him now, or we wait until Vilfredo is better?

**Comment by giovanisp** [comment]
The sooner the better. Specially securit issues on the API (vilfredo-core). I opened a new issue there.

**Comment by giovanisp** [comment]
@derekpa is the cookie bar now showing at the top of the page so we can close this?

**Comment by giovanisp** [comment]
marked urgent because or implementation (correctly as the law) prevents usage if the user has not accepted the cookies.

**Comment by derekpa** [comment]
I moved it to above the intro. See what it looks like on your various devices.

**Comment by giovanisp** [comment]
seems good.
