### ISSUE TITLE
voting screen does not have ok button.

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#236]
It is confusing UI to have to click the "close dialog" button after voting.

In fact doing this without the pop-up at all would make it much faster to go through voting on multiple proposals.

![screen shot 2015-02-23 at 11 02 28](https://cloud.githubusercontent.com/assets/1789426/6326628/96a20eee-bb4b-11e4-8ad1-5df770f23b3f.png)

**Comment by giovanisp** [comment]
Yes, getting rid of modals is already on the roadmap :-)

**Comment by pietrosperoni** [comment]
What do we do in those cases, @giovanisp ? Can we safely close this?

**Comment by giovanisp** [comment]
It is scheduled for version 2.3 as of now.  See #100. Closed as duplicate.

**Comment by pietrosperoni** [comment]
Ok, I am adding the label "Duplicate" Also black like wont fix
