### ISSUE TITLE
Current proposals should be sorted to separate voted and not voted proposals.

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#237]
Would make it easier to get through the proposals.

![screen shot 2015-02-23 at 11 05 25](https://cloud.githubusercontent.com/assets/1789426/6326663/0036d51a-bb4c-11e4-95b0-9c929abb24a7.png)

**Comment by giovanisp** [comment]
@pietrosperoni @derek ... WOw... As far I can remember we had this separation... What happened ? or is it in the middle of some open/closed issue ?

Inviato da iPad

**Comment by pietrosperoni** [comment]
It might be done, but still in the test version and not in the latest version.
So demo.vilfredo should behave well, while vilfredo not yet.

@derekpa ?

**Comment by giovanisp** [comment]
Test or nightly.
Demo will be used to test migration from rc1 to rc2 without losing data.

Inviato da iPad

**Comment by pietrosperoni** [comment]
so the final result is: have patience, this has already been solved but the solution hasn't been applied to vilfredo yet.

**Comment by giovanisp** [comment]
already fixed in next version.
