### ISSUE TITLE
can't move question to voting

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#243]
I have made 2 proposals to my own question. The "Move to Voting" was enabled. I clicked and got nothing on screen. When looking at the request, it receives a Bad request error.

![image](https://cloud.githubusercontent.com/assets/180794/6370101/0bd8f892-bced-11e4-809a-9b2ca5e4437b.png)

**Comment by derekpa** [comment]
I just tried my own question and it worked fine. Could you try again?

**Comment by derekpa** [comment]
Also was there any message set in the response

**Comment by giovanisp** [comment]
No error on video. Just the "400 BAD REQUEST" when looking at network traffic.
Anyway I tracked down the error. I am connected to the Internet via "Squid 2.7 stable" which does not support the PATCH HTTP method used in that button until it's 3.1 version (http://wiki.squid-cache.org/SquidFaq/SquidLogs#Request_methods).

So users behind Squid Proxies < 3.1 will have problems with PATCH http requests. We need to look more into the "PATCH" compatibility or decide to move it to a POST. @vvorski ? @derekpa ?

**Comment by derekpa** [comment]
Easiest just for me to convert patch to posts.

**Comment by derekpa** [comment]
no error on video?

**Comment by derekpa** [comment]
OK, form that list of commands, we should simply use POST.

**Comment by giovanisp** [comment]
I need to read more on worldwide compatibility for patch to be sure. It is a standard now, but proxies can be a problem... 


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Derek Paterson <notifications@github.com> 
Data: 25/02/2015  20:31  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] can't move question to voting (#243) 
 
Easiest just for me to convert patch to posts.

**Comment by giovanisp** [comment]
Sorry...  On screen. The page doesn't respond. See the image above. It remains that way after I click the button. 


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Derek Paterson <notifications@github.com> 
Data: 25/02/2015  20:37  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] can't move question to voting (#243) 
 
no error on video?

**Comment by giovanisp** [comment]
need to change PATCH to POST for now  :(

**Comment by giovanisp** [comment]
works.
