### ISSUE TITLE
move the "participation table" after the "submit proposal" box

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#248]
the submit proposal button is not "above the fold" for the average user. It needs to be in evidence.

**Comment by derekpa** [comment]
Is this really urgent? :-)

**Comment by giovanisp** [comment]
I am doing it

**Comment by derekpa** [comment]
You should have let me do it. If you move things around you can break things.

**Comment by giovanisp** [comment]
sorry I did not meant to break anything :-(
anyway git should merge our work, just sync the repo, I committed on "develop" directly.

**Comment by pietrosperoni** [comment]
com'on if you can work in parallel on different things, it will all be much faster.

**Comment by derekpa** [comment]
@pietrosperoni huh?

**Comment by derekpa** [comment]
@giovanisp moving things can break knockout bindings.

**Comment by giovanisp** [comment]
I hate knockout :)

**Comment by pietrosperoni** [comment]
that's why it's called "knockout".

**Comment by giovanisp** [comment]
LOL
