### ISSUE TITLE
main text of proposals should have a text limit with visual hint for users

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#25]
Right now it is 1000 characters like the abstract. But the abstract should be shorter. Like this it makes no sense.

**Comment by giovanisp** [comment]
We will need to test with long proposals. In fact the readability range progress bar was indipendant from the lenght of the proposal (10k chars) and thus would work well on any lenght. now, applying only the lenght, it barely passes 1%. Which is useless for the body. maybe good for the abstract.

An option would be to use the median of orevious proposals for the same question to make the progress bar refer to the median lenght of other proposals, so who's writing knows more or less if he has to write more or less text to convey his message in a way similar to others. @pietrosperoni ?

**Comment by giovanisp** [comment]
BTW @vvorski propose target users/personas here: https://vilfredo.org/question/11

**Comment by pietrosperoni** [comment]
Hmm, no I don't think the median would work well here. Some proposals are just shorter than others. And it does not make much sense to ask for proposals who are shorter to be longer.

What could be done is to take some statistics on the varoius length, and show them. So when you are writing 0-100 characyters, in general people will take on median x time to read it.
Oh, now you have written 101-200 characters. For this the time people take is ...
And so on.

Soon we would find that proposals over a certain length obtain LESS attention, as people simply skim them. Theny they would learn to write less.

**Comment by giovanisp** [comment]
Awesome!!!! I loved that!

**Comment by giovanisp** [comment]
I have opened #252
