### ISSUE TITLE
better phrasing on home tooltips

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#250]
In the home dashboard, when mousing over the proposal title, let's change the phrases to:

"X out of Y participants submitted N proposals" for proposals and
"X out of Y participants already voted" for voting and
"X out of Y participants contributed" for results area.

**Comment by derekpa** [comment]
whats the "home dashboard"?

**Comment by pietrosperoni** [comment]
I suppose the homepage where you can see all the questions you are participating on.

**Comment by derekpa** [comment]
So he means mousing over the QUESTION titles...

**Comment by derekpa** [comment]
ok

**Comment by pietrosperoni** [comment]
LOL, yes!
(I am not the only one make confusions :-) )

**Comment by pietrosperoni** [comment]
Ok, I checked it
