### ISSUE TITLE
Proposals alignment problem

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#255]
Proposals with different title height have alignment problem when shown. Perhaps we should use a grid in a "pinterest-style" to solve this? see the code here http://cssdeck.com/labs/css-only-pinterest-style-columns-layout

![image](https://cloud.githubusercontent.com/assets/180794/6443782/ae719680-c0f9-11e4-8ced-71d189628cc5.jpg)

**Comment by derekpa** [comment]
Or we make all the title bars the same height

**Comment by giovanisp** [comment]
that would make us lose a lot of space, and fixing height might be a problem for zooming the page. we can do it now, but some time in the future we'll need a refactoring.

**Comment by derekpa** [comment]
Yes, its better just to fix the layout to cope.

**Comment by giovanisp** [comment]
ok for now.
