### ISSUE TITLE
lost avatar after RC2 update

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#256]
Need to look into why, and make sure it does not happen again in the next update:

![image](https://cloud.githubusercontent.com/assets/180794/6444927/095e9000-c101-11e4-9c15-69f7d58e2d24.png)

**Comment by derekpa** [comment]
Lost? You uploaded your avatar to test. This is a different site.

**Comment by giovanisp** [comment]
AHAHAHAHAHH...

**Comment by pietrosperoni** [comment]
wontfix? What? There is no bug.

**Comment by giovanisp** [comment]
Yeah I know , I know... you can even delete that :-)

Inviato da iPad
