### ISSUE TITLE
on voting page, voted and non-voted proposals are mixed

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#257]
apart the #255 alignment problem. The current votng phase does not separate the voted and unvoted proposals with the results triangle between them... wasn't that expected ?

![vilfredo which are vilfredo s target audience](https://cloud.githubusercontent.com/assets/180794/6445258/0ad4a9b8-c103-11e4-9137-98aac1c2393f.png)

**Comment by pietrosperoni** [comment]
I am surprised, didn't we already put all the new voted, last, and the unvoted before. With something in between?

**Comment by derekpa** [comment]
Results triangle is not shown until ALL proposals have been voted for

**Comment by giovanisp** [comment]
Ok for the triangle. What about the separation between voted and non-voted proposals?

**Comment by derekpa** [comment]
Well that should be on test now.

**Comment by derekpa** [comment]
I take it you are looking at test and not the live site? :-)

**Comment by pietrosperoni** [comment]
Why has this been assigned to me, @giovanisp, @derekpa ?
By the way the live site was just updated, so there should be no difference between live site and test site.

**Comment by giovanisp** [comment]
Done.
