### ISSUE TITLE
optimize spacing and layout on questions in various phases

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#260]
Our pages are taking too much space to show the main actions to users. Here is a proposal of mockups to optimize the spacing and information on the various phases. *Please note* how the warnings vary according to how many people voted/participated in each phase:

### writing phase

I propose giving the user the same information as in the home, plus indications on how to behave based on number of participants and their actions. See the sequence below:

![image](https://cloud.githubusercontent.com/assets/180794/6461562/2bbbad36-c1a1-11e4-8a38-8a75c8db13d1.png)

![image](https://cloud.githubusercontent.com/assets/180794/6461567/3ca86792-c1a1-11e4-827b-10d4fbd28408.png)

### voting phase

similarly for the voting phase:

![image](https://cloud.githubusercontent.com/assets/180794/6461574/4b56e002-c1a1-11e4-9142-40a4b0d468f3.png)

![image](https://cloud.githubusercontent.com/assets/180794/6461577/55688848-c1a1-11e4-866f-73c21ce14ec2.png)

![image](https://cloud.githubusercontent.com/assets/180794/6461578/5f81977a-c1a1-11e4-861b-84ca4eb451d3.png)

### results phase

If a question is on results phase, I propose linking directly to the results page, and providing a link to "view the question page". This way the user is taken directly to the results instead of doing another click as it is now.

![image](https://cloud.githubusercontent.com/assets/180794/6461435/321c0226-c1a0-11e4-8221-868b4ccd4fc0.png)

**Comment by pietrosperoni** [comment]
Neat. I wonder if we should not first decide a standard way with which Vilfredo communicates to people to tell them 
a) the situation
b) what they should do (so like a tutorial)
c) what they should do (like key players)

Maybe we could have three different styles. One for Vilfredo presentation of the situation, one with Vilfredo as a teacher, one with vilfredo as moderator. Maybe we could even have three personalities appear (signing: Vilfredo, Federico, Damaso: the three names of Vilfredo Pareto)

**Comment by giovanisp** [comment]
> standard way with which Vilfredo communicates to people to tell them 
>a) the situation

absolutely needed. I am trying to make it more readable for the average user with these changes. A work of standardization would enter into a UI/UX redesign.

>b) what they should do (so like a tutorial)
>c) what they should do (like key players)

Tutorial and Key Players are in the roadmap and I would put their own requirements in their own issues so when it comes to implementing all information is there.


>Maybe we could even have three personalities appear (signing: Vilfredo, Federico, Damaso: the three names of Vilfredo Pareto)

Honestly, I think one is enough, creating too much personification can confuse average users (that might do not even know who is Vilfredo, let alone Federico/Damaso :-)

**Comment by giovanisp** [comment]
In the light of use cases specified in #222, the First Phrase for each mockup should trim the "Once you have Xxxxxxxxxx" and keep only "You can xxxxx....." message.

**Comment by giovanisp** [comment]
Ok for the Alert Boxes. Only missing the top lines:
![image](https://cloud.githubusercontent.com/assets/180794/6668469/77ca7188-cbf3-11e4-8f99-b236879da372.png)

Also, Edit buttons (to edit a question, or delete) should appear in the button bar, without a H2 Section for it. We can color these buttons differently if necessary, to convey a different type of actions is going to happen.

**Comment by giovanisp** [comment]
derek... do we still miss the top messages ?  I see this:

![image](https://cloud.githubusercontent.com/assets/180794/7539277/372f3dde-f5a6-11e4-8afb-5b5f3c0310f9.png)


instead of this:

![image](https://cloud.githubusercontent.com/assets/180794/7539291/4f7cf11a-f5a6-11e4-8c87-302e19795b13.png)

**Comment by derekpa** [comment]
Have you cleared your cache recently and are you using test?

![screen shot 2015-05-15 at 15 41 38](https://cloud.githubusercontent.com/assets/1368533/7655040/0497f80c-fb19-11e4-989a-1673529a1b66.png)

**Comment by giovanisp** [comment]
Your picture is different from this posted above:
https://cloud.githubusercontent.com/assets/180794/7539291/4f7cf11a-f5a6-11e4-8c87-302e19795b13.png

**Comment by giovanisp** [comment]
The 3 lines on the right of the picture leaves more vertical screen real estate left.

**Comment by derekpa** [comment]
Ah, hadn't noticed the text was aligned right.

**Comment by derekpa** [comment]
Nicer :-)

**Comment by giovanisp** [comment]
definitely.
