### ISSUE TITLE
Can't go to results page, only myself in the proposal

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#261]
Why can't I move this question to results?
http://test.vilfredo.org/question/13

I moved it to voting it says I am the only one participating....

**Comment by derekpa** [comment]
Because at the moment we need at least 2 people to have voted :-)

**Comment by giovanisp** [comment]
Yeah so I can't also be allowed to move to voting if there aren't at least 2 participants, right?

**Comment by giovanisp** [comment]
I need to be able to go to results even if I am the only one voting. See related issues.

**Comment by giovanisp** [comment]
#187
