### ISSUE TITLE
Avoid indiscriminate invitations by checking all boxes

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#268]
from @pietrosperoni There should be no way to invite indiscriminately. The list of users in invitation screen shows me even people I don't know. The best way should be removing that list and allowing to insert usernames directly in the email field, just like google invitation screens allow (with autocomplete).

**Comment by pietrosperoni** [comment]
I really don't know what is the "best way". But definitely we must avoid getting into spam hell where people start to ignore vilfredo messages, and google start to catalog it as spam. Once we are there we will have much greater difficulties with everything. This is important. We should not abuse of this EVEN in the test site. Google makes no difference.

@derekpa what are the rules right now? Who is present in the list that we see?

@giovanisp maybe the list is all the people you worked on a question in the past. This is how the old Vilfredo use to work. But we should think something better.

I started receiving so many invitations, I understood there was a button that would check all the boxes in the list, so I was alarmed. But apparently there isn't. 

Maybe the best way is to write the names (or emails) with vilfredo autocompleting the names.

Another graphical idea, we could have the names in one list and people need to drag and drop people in the list of invited people. And they have to do it one by one.

I would suggest that as soon as we have a multigeneration vilfredo, we ask this as a question there.

**Comment by giovanisp** [comment]
>This is important. We should not abuse of this EVEN in the test site. Google makes no difference.

we can (must) use robots.txt in the test, nightly and demo sites to disallow search engine crawling. Only the live site (and dev) is to be indexed.

>the list is all the people you worked on a question in the past. 

probably, but does not work, I don't know who they are and they appear on every new invitation screen.

>I understood there was a button that would check all the boxes in the list, so I was alarmed. But apparently there isn't.

There isn't.


>Maybe the best way is to write the names (or emails) with vilfredo autocompleting the names.

Faster way. Kind of standard these days.

>Another graphical idea, we could have the names in one list and people need to drag and drop people in the list of invited people. And they have to do it one by one.

Cute. Probably harder on front-end design, perhaps as an enhancement in 2.x ?

>I would suggest that as soon as we have a multigeneration vilfredo, we ask this as a question there.

Agree, you can create it now and move it on later.

**Comment by derekpa** [comment]
@giovanisp What people are shown that you don;t know?

**Comment by giovanisp** [comment]
lanta
stefno
Pietro3

I don't remember in my list...

**Comment by pietrosperoni** [comment]
lanta is a person from the Italian Pirate Party
Stefno is probably Stefano Stortone. I think you know him.
Pietro3 is my third username that I use to test,

**Comment by giovanisp** [comment]
the fact is not that I "don't know who they are",  but ... in the context of Vilfredo, why they show up to me if I don't remember sending them direct invitations to my questions?  Are being added only because "they have participated in a question where I was participating as well" ?  If so, this list will get very big.

**Comment by pietrosperoni** [comment]
indeed, the aim when I started in in Vilfredo 1 was to let it grow. We should decide how do we decide what should go in this list

**Comment by giovanisp** [comment]
the most trivial answer would be "the most frequent users you find yourself engaged".
but I would split this into a quick solution for now (including limiting the size of the list), and a "research" issue for 2.2 or 2.3 that will have improvements in invitation process.

**Comment by pietrosperoni** [comment]
Not sure why this is assigned to me, @giovanisp ?

**Comment by giovanisp** [comment]
@derekpa what are you implementing right now for 2.0.0 ? So we can split enhancements in future issues ...

**Comment by derekpa** [comment]
@giovanisp  what  you see here

**Comment by derekpa** [comment]
@giovanisp  the way it should work, unless there's an error, is an associated users is anyone who has participated in a question you have participated in.

**Comment by derekpa** [comment]
@giovanisp Example, lanta... you both participated in question 4.

**Comment by derekpa** [comment]
"Are they being added only because "they have participated in a question where I was participating as well" ?  If so, this list will get very big." --- yes, that is the setting for now.

**Comment by derekpa** [comment]
For now I'll initially show users related by dirct invitation rather than participation.

**Comment by giovanisp** [comment]
Yes this is better than before. In next releases lets make it smarter by counting the frequency of interactions and proposing "recurrent" people that decide together.
