### ISSUE TITLE
UI without icons or left-aligned (clear dashboard)

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#269]
after adding invites, the UI on the home is messy. This screen goal is to present all questions the user can participate. As of now this is my 1366px width view: 

![image](https://cloud.githubusercontent.com/assets/180794/6554255/d7750bd8-c659-11e4-9781-d5c2d63f669d.png)

Elements are not aligned and the "Ask New Question" button also change position if the screen is resized.

A tablet view (is not responsive):
![image](https://cloud.githubusercontent.com/assets/180794/6554192/42ffe2e8-c659-11e4-8a59-66987e8de766.png)

I propose we either remove the "2 columns" in the green panel and keep the list left-aligned as in the mockup #174 :
![image](https://cloud.githubusercontent.com/assets/180794/6554222/7aa7015e-c659-11e4-8def-0093d56b6a93.png)

Or try to fix the issues above.

**Comment by giovanisp** [comment]
Also, the Accept/reject icons should be placed before the question, so if there are more than one invitation the labels are aligned.

**Comment by giovanisp** [comment]
I committed a version without the icons, just to clear the UI a little and check how it looks. We could play with line-heights as well  @vvorski  ???

**Comment by vvorski** [comment]
Hi,

Where should I look at what?

I want to contribute to vilfredo but I need my work batched up so I can do a few hours once a week. I am not able to keep up on things on a day-to-day basis...

When will be a good time to do another usability/UI review? Which instance should I do it on?

Kind Regards,

Victor Vorski
victor@vorski.com　skype:vvorski

**Comment by giovanisp** [comment]
You should register (if not already) and use http://test.vilfredo.org 
if you can't register, let me know and I'll send you an invitation.


Inviato da iPad

> Il giorno 09/mar/2015, alle ore 12:54, vvorski <notifications@github.com> ha scritto:
> 
> Hi,
> 
> Where should I look at what?
> 
> I want to contribute to vilfredo but I need my work batched up so I can do a few hours once a week. I am not able to keep up on things on a day-to-day basis...
> 
> When will be a good time to do another usability/UI review? Which instance should I do it on?
> 
> Kind Regards,
> 
> Victor Vorski
> victor@vorski.com　skype:vvorski
>

**Comment by derekpa** [comment]
I added the style used to layout the question to the new invitations so they align properly.

**Comment by derekpa** [comment]
I would also put back the icons and remove the author name, displaying that in a tooltip as per the invites.

**Comment by giovanisp** [comment]
Here is a view on mobile 
![screenshot_2015-03-10-12-09-36](https://cloud.githubusercontent.com/assets/180794/6573841/426a70ca-c71f-11e4-9993-b4dd7a386e8f.png)

**Comment by derekpa** [comment]
OK, so the cookies bar shouldn't be showing...

**Comment by derekpa** [comment]
Also, I would say it would look way better with the icons and less text.

**Comment by derekpa** [comment]
We could move the Ask Question button to the top centre then have two columns, one for new questions and one for new invitations.

**Comment by derekpa** [comment]
Try it now.

**Comment by giovanisp** [comment]
Aren't new question the same as "propose an answer to a question" ?
i was thinking about the top green panel only for invites.

**Comment by derekpa** [comment]
I just did it the way it was done on the original vilfredo, where new questions appear at the top until they have a proposal.

On a phone I would actually move the invites above the new questions.

Or, we could just move new questions with no proposals down to the writing section.

**Comment by giovanisp** [comment]
> Or, we could just move new questions with no proposals down to the writing section.

That's better IMHO.

**Comment by derekpa** [comment]
OK, I put that layout on test.

**Comment by giovanisp** [comment]
Seems good. Can we just make the questions appear in full text and not trimmed wit "..." ?

![image](https://cloud.githubusercontent.com/assets/180794/6593733/7130a958-c7db-11e4-90d7-5e09f95b24e5.png)

**Comment by derekpa** [comment]
Well we can now, now that we have the space....
