### ISSUE TITLE
After you are in, it should tell it.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#27]
Something like: "Welcome Carlo!" Written in big and disappearing

**Comment by giovanisp** [comment]
Missing photo upload and get rid of border in the logout button. 
Align spaces between buttons in the top bar.

**Comment by giovanisp** [comment]
photo upload and retrieval is a new feature (client/core).

**Comment by pietrosperoni** [comment]
How urgent is photo, @giovanisp ? I tend to think we first should have a system that can be used. Then we make it pretty. ANd photo are definitely part of the prettifying part. So I was thinking about 2.0.1.

Right?

**Comment by giovanisp** [comment]
yeah, you're right.

**Comment by giovanisp** [comment]
About and contact were moved to footer.

**Comment by pietrosperoni** [comment]
Is this issue still open? What remains to be done on this?
@giovanisp , @derekpa ?

**Comment by derekpa** [comment]
get rid of border in the logout button ??? Won't that look odd?

**Comment by giovanisp** [comment]
It should look like the above mockup when the user photo is ready.
If it does not look good, we can revert. As of now it also looks odd :-) we can always use another color but I'd rather stick with 3-4 main palette colors.

**Comment by derekpa** [comment]
I added the user photo already - its on test.

**Comment by derekpa** [comment]
OK, I removed the border of the logout button. You think we really need the search box for the release, or make another issue for that?

**Comment by giovanisp** [comment]
Another issue for the search box.
