### ISSUE TITLE
Client allows voting multiple 

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#270]
The client allows me to vote multiple times?

![screen shot 2015-03-09 at 14 42 20](https://cloud.githubusercontent.com/assets/1789426/6557145/b6bc6fba-c66a-11e4-9ce4-e20f86dc1a7f.png)

**Comment by giovanisp** [comment]
confirmed (it is a UI glitch). If you click fast to change your vote, the SVG graph keeps its old drawings. Need to make sure the database gets hit only once.

**Comment by derekpa** [comment]
Huh? Could you explain this a little clearer @giovanisp?

**Comment by giovanisp** [comment]
Open the voting triangle.
Make very fast clicks in different parts of the triangle (I used Chrome latest version).
The triangle shows duplicated votes in the triangle drawing.

Probably a refresh glitch?

**Comment by derekpa** [comment]
OK, looks like a Chrome issue. And no there are not multiple votes, it's just not refreshing properly on chrome.

**Comment by derekpa** [comment]
>Need to make sure the database gets hit only once.

So need to decide when the vote gets sent. If people are going to click all over the map very quickly and we want to reduce bandwidth we need to actually send the vote when the user shuts the triangle or clicks a button 'save vote'.

**Comment by vvorski** [comment]
I've always thought that it was strange there is no save button, just close window. That's very nonstandard...

V/.

**Comment by giovanisp** [comment]
> we need to actually send the vote when the user shuts the triangle or clicks a button 'save vote'.

I suggested it some time ago... we did not agreed on having a save button. But I am for it, it was a performance issue (if you check developer tools - network you see how bad it performs with multiple clicks).

> Not sure how well it would work with multiple aborting.

What is multiple aborting ?

**Comment by derekpa** [comment]
@vvorski non standard? It's interactive. Why would that be non standard?

**Comment by derekpa** [comment]
Multiple aborting means if a user clicks again quickly we could abort the previous Ajax call

**Comment by derekpa** [comment]
The aim originally was to have the triangle interactive. You click, your vote is recorded. We didn't envision people making multiple fast clicks on a regular basis. 

You think, you click and maybe you drag to change it. 

But making the finagle interactive was an obvious design decision.

**Comment by vvorski** [comment]
For me it looked strange, I was searching for a "OK" button.

On a page with multiple options auto save makes sense.

In fact I think the whole voting would work better without a pop-up.

V/.

**Comment by giovanisp** [comment]
Yes, getting rid of the modal box is in our priorities for the question voting page.


> Il giorno 11/mar/2015, alle ore 21:29, vvorski <notifications@github.com> ha scritto:
> 
> For me it looked strange, I was searching for a "OK" button.
> 
> On a page with multiple options auto save makes sense.
> 
> In fact I think the whole voting would work better without a pop-up.
> 
> V/.
>

**Comment by derekpa** [comment]
Well for me the idea of clicking on the triangle then having to click save would be odd, and to be honest, with fast internet just clicking and the vote is saved is what I imagine most people would expect.

**Comment by derekpa** [comment]
Why are modals so bad?

**Comment by derekpa** [comment]
Also, remember the client does not allow multiple voting. Its just on chrome things don;t tidy up so well at the moment.

**Comment by vvorski** [comment]
On 12 Mar 2015, at 00:18, Derek Paterson <notifications@github.com> wrote:
> Why are modals so bad?
> 

Interesting question. I don't think that this one modal is so important. In the grand scheme of things Vilfredo needs a total UI overhaul with a professional designer so spending time focusing on details now is probably not useful use of time. 

But since to me instinctively modals are bad I thought I'd try to explore where this comes from.

http://stackoverflow.com/questions/361493/why-are-modal-dialog-boxes-evil

"When ... the mode requires the user to possess information he does not have readily available... then it will cause the user hardship, either forcing him to revert to a previous mode or guess at the proper action with potentially undesirable results."

In the context of Vilfredo the user is probably going to compare his votes on different questions so having to switch between pop-ups to do this would be painful, no?

http://stackoverflow.com/questions/361481/when-are-modal-dialogs-truly-necessary

"Use Cases for Modal Dialogs

	� blocking the application flow until information required to continue is entered, as for example a password in a login process.
	� collecting application configuration options in a centralized dialog. In such cases, typically the changes are applied upon closing the dialog, and access to the application is disabled while the edits are being made.
	� warning that the effects of the current action are not reversible. This is a frequent interaction pattern for modal dialogs, but it is also criticised by usability experts as being ineffective for its intended use (protection against errors in destructive actions) and for which better alternatives exist."

I don't think the current usage fits either of the above three recommendations.

The following article has many good examples and explanations - and as I expected almost all of them have a "save/cancel" button. I do think that "press X to save" is not a standard UI pattern:
http://uxmovement.com/forms/best-practices-for-modal-windows/

https://developer.appway.com/screen/ShowSingleRecipe/selectedRecipeId/1390246496349
"Typically, modal windows are discouraged in user interface design, because they interrupt users and force them into doing a specific action. What's more, modern operating systems have trained people to instinctively and automatically dismiss dialog boxes (for example, interaction designer Aza Raskin notes that "interfaces that don�t respect habituation are very bad" � there are extensive studies about this). Many people simply don't read modal dialog boxes, or are confused by them. 

In almost all cases, there is no need to force users into specific actions. As a result, modal windows introduce unnecessary pain points for your users. 

Instead, you should aim to create modeless user interfaces. Modeless user interfaces allow users to change their mind at any point. They are not forced into a specific set of actions. 

Modal windows also cause another problem: they don't work well on devices with small screens. Modal windows eat up screen space, since they introduce additional user interface elements. If the screen is small to begin with (for example, when the user is using a phone to access your App), the content inside the modal window is even smaller. This is particularly bad if the content doesn't fit inside the screen, and you need to show scrollbars. Nested scrollbars do not work well on mobile devices, since people expect to be able to scroll the whole screen by swiping with their fingers. 

So modal windows provide a bad user experience, and don't work well on mobile devices. Fortunately, there are almost always better solutions that you can use instead of a modal window. These alternatives are completely modeless, and work well on any device. 
"


Some further reading:
http://cloudmanic.com/blog/51/modal-windows-are-for-chumps
https://strategicapps.wordpress.com/2013/10/17/modal-window-debate/
http://ux.stackexchange.com/questions/12637/what-research-is-there-suggesting-modal-dialogs-are-disruptive

**Comment by giovanisp** [comment]
wow... I have no other to add after @vvorski 's great research. I follow his same principles on this matter. And agree that we will need UI overhaul in the future. For now, we can fix what we can to make it as usable as possible, based on our "limited" experience.

**Comment by derekpa** [comment]
OK @vvorski, shall read though your very thorough response later :-) 

As to why modals have been used so much within the UI so far, first it was a quick way of building a client against which to develop the API and the core, which was actually the main purpose of this client.

As for the voting triangle, it needed to be large so displaying as a modal was the easiest way to do this.
To compare votes, for now you would use the Results Triangle.

**Comment by derekpa** [comment]
Also, your argument is that modals are mostly a bad choice but not always. Reading through the arguments against them, yes I can agree, mostly they are bad. I would say that for the triangle a modal was not however such a bad choice - except for how they work on small screens - as the intention was indeed to focus the user's attention on a graphic representation of how much they understand and agree on somthing within the context of their other votes.

I also disagree that a save button should 'obviously' be necessary to save your coordinates just because the triangle appears in a modal or for other reasons. 

But we'll see. We'll have to balance the triangle with bandwidth limitations, user expectations and redesign for workflow.

**Comment by pietrosperoni** [comment]
One thing I would want to add. One of the reasons why modals are considered bad is because "they force the user into doing a specific action".
But this is exactly what we want to do in Vilfredo. Basically we are aiming to a direction where the user is guided over what to do. This to avoid that he only evaluates the proposals of his friends, or only the easy to evaluate proposals.

We have been discussing this with @derekpa long time ago, and we came to the conclusion that we wanted to have a single page responsive where the user interacted with the page, and the page would ask specific actions to be done:
choose among those two,
explain this,
evaluate this other,
ask this person what's wrong with this proposal. 
As you evaluate negatively this proposal, please explain what's wrong with it (so others can make it better)

This is not Facebook, Vilfredo is a proactive AI moderator, as such it is He who has the power and guides the discussion.

I am not sure what UX and UI better achieve this aim, but I am sure this is where we are heading if we want Vilfredo to fulfil its potential of merging different point of views in a fair way.

So knowing all this, @giovanisp and @vvorski , do you still believe Modals are evil? How else would you achieve this?

**Comment by giovanisp** [comment]
I think it is unproductive to keep discussing UI/UX on something we have still to talk a lot about. We will probably need to design more than one UI for the triangle and test what it works best with users (called A/B testing). So, I would do a step back to the title of this issue, which deals with the "multiple voting", which, as I understood, should be solved by now. Is that correct @derekpa ?

**Comment by derekpa** [comment]
No. Its a chrome issue i have to look at. It seems to happen when the person voting is clicking very fast, which is not normal behaviour.

**Comment by giovanisp** [comment]
seems to work pretty well !!
