### ISSUE TITLE
No way to match the voting graph to the proposals...

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#271]
The graph just has numbers on it...

![screen shot 2015-03-09 at 14 45 18](https://cloud.githubusercontent.com/assets/1789426/6557216/5eb64902-c66b-11e4-876f-726d02184651.png)

**Comment by giovanisp** [comment]
@derekpa  need to add the IDs before the proposal titles in the Proposal Boxes, and find a better way to present the whole screen.

**Comment by pietrosperoni** [comment]
Adding the numbers if the first step, but we really need to be able to write something small on the graph that gives an idea.
For example if the title instead of 50 characters long was 5 times 10 characters then we could put them in five lines.

Ok, I never claimed I knew how to do UI.

**Comment by vvorski** [comment]
Perhaps just leave until the big UI redesign?

V/.

**Comment by pietrosperoni** [comment]
We can start to add the ID, and the rest on the big UI redesign

**Comment by derekpa** [comment]
ID added to proposal boxes
