### ISSUE TITLE
fix hamburguer icon and dialog on smartphone

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#273]
![image](https://cloud.githubusercontent.com/assets/180794/6593329/f47d98a6-c7d7-11e4-870c-f2ce075781ce.png)

**Comment by giovanisp** [comment]
@derekpa  need LESS compiling+deploy on test

**Comment by giovanisp** [comment]
needs lLESS compile + push to test

**Comment by giovanisp** [comment]
hmm... I think the LES file was not compiled correctly, it seems it lost some of my changes. The black color is showing instead of the dark gray: 
![image](https://cloud.githubusercontent.com/assets/180794/6636987/6e083034-c975-11e4-9f17-5c64ebf28573.png)

![image](https://cloud.githubusercontent.com/assets/180794/6636991/73dddef0-c975-11e4-8d44-c533a6ed53cd.png)

**Comment by giovanisp** [comment]
needs LESS compiling and page deploy on test.

**Comment by derekpa** [comment]
OK, done.
