### ISSUE TITLE
fix cookiebar on smartphone

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#274]
![image](https://cloud.githubusercontent.com/assets/180794/6593347/266007dc-c7d8-11e4-92ba-7d23c916ce1a.png)

**Comment by giovanisp** [comment]
@derekpa  need LESS compiling+deploy on test

**Comment by derekpa** [comment]
Navbar's now white on test

**Comment by derekpa** [comment]
OK, I tweaked it. Removed the border (looked awful on the laptop) and made the colour black.
