### ISSUE TITLE
on second generation, I have 2 proposals and can't move the question

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#276]
See the following case:  
1 inherited proposal, and one new proposal = 2 proposals. Vilfredo doesn't allow me to move.

![image](https://cloud.githubusercontent.com/assets/180794/6669064/4ba5f0ce-cbf7-11e4-8f73-3eefbb474773.png)

**Comment by derekpa** [comment]
Yes, till now we've insisted on two NEW proposals which makes sense for just 1 generation. Fr gen 2 and up I would suggest setting it for at last one new.

So logic wise that would mean we allow moving to voting so long as there are a minimum of 2 proposals in total and at least 1 new one.

**Comment by giovanisp** [comment]
@pietrosperoni what about if 2 or more proposals are inherited from previous generations and no new proposals are written? can it be moved to voting again (like a second round?)

**Comment by pietrosperoni** [comment]
No. Because the results would be the same. No need to bother everybody with voting.
The key thing about using the triangle is that we gather enough info on the first round that we do not need to go through the second round (as instead happens in liquid, airesis, and so on).
