### ISSUE TITLE
move the person who invited the user to the correct place

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#279]
On test.vilfredo.org the person who invited the user to a question should appear after the question text.
![image](https://cloud.githubusercontent.com/assets/180794/6705714/d9c4cb58-cd57-11e4-8d6d-59eb94fcaefa.png)

**Comment by pietrosperoni** [comment]
have we already introduced invitations not by the author?

**Comment by giovanisp** [comment]
Not yet but the solution applies now to both cases (the author is the user inviting). Whenever it is possible, let's code keeping in mind future development.

**Comment by giovanisp** [comment]
Cool! done.
