### ISSUE TITLE
I can not access to a question

### ISSUE THREAD

**Issue by lazanna** [fairdemocracy/vilfredo-client#281]
I received this invitation:
"... User Pietro has added you to the question How should Vilfredo collaborate with Airesis.    
    http://vilfredo.org/question/37... "
I display the title in the list of questions, but I can not access this page.

**Comment by pietrosperoni** [comment]
are you logged in with the correct username @lazanna ? You can only see a question if you are logged in.Rremember also  that you have made about 4 different usernames to test Vilfredo. :-)

**Comment by giovanisp** [comment]
Anyway, we will need to add the invited username like "Hi username1 (or email if not registered), username2 has invited you ...." and even if the user isn't logged in when clicks on the invitation link, there should be a very easy way to login or register and continue the invitation process.

**Comment by lazanna** [comment]
whatever was the problem, it was not for the use of avatars wrong.
avatars "in-fang" and "sp-fang" do not even listed the questions that you have not been invited.

**Comment by pietrosperoni** [comment]
Yes, in fact I only invited you with one avatar. So, could you enter in the page now?

@giovanisp, @derekpa I suspect the problem is that the link is just a plain link to the question. It works if someone is logged in, but it does not work if someone is not logged in. 
@derekpa , can we have a link that if you click on it, it will automatically log you in?

**Comment by pietrosperoni** [comment]
@giovanisp , is this enhancement or bug? Where should it go? :-)

**Comment by giovanisp** [comment]
Bug. as stated, if a user is invited and not logged in he either is presented with login (or registration) and then goes to the destination URL.

**Comment by lazanna** [comment]
The problem may be caused by Ghostery, on another installation of Firefox, I can log into my quest.
But strangely, It do not block access to test quests I had done

**Comment by pietrosperoni** [comment]
I am lost @lazanna . What is the problem? 
You have ghostery on FF. You can log in, but you cannot see the question? Can you try to delete the cookies and start again? 
Do you prefer to explain it in Italian?

**Comment by lazanna** [comment]
I have disabled Ghostery, but still can not access the question "How Should Vilfredo collaborate with Airesis".

Close this issue, I will enter using the other computer.

**Comment by pietrosperoni** [comment]
We had a similar issue with my father some time ago. What solved it for him was that he needed to clear his cache.
