### ISSUE TITLE
Fix results triangle voting for one user

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#282]

**Comment by giovanisp** [comment]
not sure what it is....

**Comment by derekpa** [comment]
This is another I added for me, The reuslts triangle now allows a single voter to drag and update his vote. Before it was not possible.

**Comment by pietrosperoni** [comment]
Hi @derekpa . If you have three voters, and a central one has the vote that is in the same position of the result (being the median), can this person still change his vote on the result triangle?

**Comment by derekpa** [comment]
Yes

**Comment by giovanisp** [comment]
@pietrosperoni  up to you. Is this fine for you ?

**Comment by pietrosperoni** [comment]
Yes, tested. It works fine. We still have a problem with proposals that cannot be voted above each other. Which means some proposals cannot be voted in some positions. But the moving side works perfect, thanks (and by the way, i asked myself a question that I needed, and was good as a self brainstorming session)

**Comment by giovanisp** [comment]
Open a bug/enhancement for a next version for what is to be done on this front later. add the "not utgent" label if it is a non urgent issue.
