### ISSUE TITLE
"Agree" button on a question does not make sense.

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#284]
What does it mean to "agree" with a question?
![screen shot 2015-03-26 at 12 10 37](https://cloud.githubusercontent.com/assets/1789426/6845956/c1dce812-d3b1-11e4-8c3f-21c283b0a979.png)

**Comment by pietrosperoni** [comment]
"I also had the same question"? :-)
or
I also would like to know.

How would you rephrase it?

It is interesting how many people have a specific doubt, so I think we should measure it. But maybe calling it "agree was not correct.

**Comment by giovanisp** [comment]
Let me be creative here.... what about using  a "+1" button ? :-)

**Comment by pietrosperoni** [comment]
+1

**Comment by giovanisp** [comment]
handed to @derek for next release

**Comment by giovanisp** [comment]
the "v" icon does not resemble a "+1" or "like"... let's use the simple CSS without icons,  just "+1" next to it, perhaps showing the total number of "+1's" received...  Or the like button but with the sum number next to it so it is relevant of how many other people find that question interesting.

**Comment by derekpa** [comment]
V icon? Its a tick....

**Comment by giovanisp** [comment]
nice !!
