### ISSUE TITLE
comment lost silently when switching to proposal

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#286]
Test case:
-) click on comment button on proposal
-) write comment
-) click on proposal

comment lost silently.

Since this screen does not display the full proposal (for me that is awful also), need to switch to it when writing a comment this makes the comment silently disappear.

Solution:

Either:
-) Whenever a user is about to switch away from a screen which will result in their input being lost they should be prompted with a pop-up. 
or
-) Just save the in-progress text so the user doesn't have to worry about this. (asana does this, never looses your in-progress comments anywhere. the downside is sometimes you type it half way, forget you didn't send it and only realise this days or weeks later.)

![screen shot 2015-03-26 at 12 26 04](https://cloud.githubusercontent.com/assets/1789426/6846176/ec0bafb8-d3b3-11e4-8d99-792b71172f62.png)

**Comment by pietrosperoni** [comment]
@vvorski since you called this bug, check out if it still does it on test.vilfredo.org :-)

Thanks

**Comment by vvorski** [comment]
looks ok now. well within the constraints of the existing vilfredo UI...

**Comment by pietrosperoni** [comment]
Thanks :-). One thing at a time :-)
