### ISSUE TITLE
Vilfredo does not send notifications when proposals move from writing to voting.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#287]
We have now several questions that are on voting, but no one realised it.

I am not sure if this is an enhancement because we did not have it, or a bug because we had it but it's not working. Anyway, @giovanisp I let you decide the milestone. For me I think this should be ready yesterday :-)

**Comment by giovanisp** [comment]
I moved one question of mine to voting and did not get any email.
Are we sending email to everyone else except the author? If so, can you move one of your questions on test, @derekpa ?
