### ISSUE TITLE
Voting box does not display full proposal...

### ISSUE THREAD

**Issue by vvorski** [fairdemocracy/vilfredo-client#288]
It is hard to vote without seeing the full proposal forces me to click back to the full proposal view making the voting process really interrupty...

What I think is needed is a screen which allows people to just go through, read each proposal vote, and move to the next.

The usage flow needs to be "read, vote, next, read, vote, next" in fact maybe don't even need "next" as it could move to the next one automatically after voting.

![screen shot 2015-03-26 at 12 31 49](https://cloud.githubusercontent.com/assets/1789426/6846221/3c4fe430-d3b4-11e4-90ef-4f769097907b.png)

**Comment by pietrosperoni** [comment]
Hi @vvorski , the idea of having a flow is something very high in the todo list, but we still need to clarify it well. In particular in the flow it is important that people after they have voted can comment on the proposal. You know how in sociocracy it is important to give a reason why you are against a proposal. Here we need something similar. So if you vote on the left it should ask you to write why you do not like the proposal. and if you vote down you should be required to ask a question.

So something like:
read, read comments, vote, write, next
read, read comments, vote, write, next
read, read comments, vote, write, next


We could have some questions were comments are not available or not obligatory, and see how the system works. Maybe for some questions it is better.

**Comment by vvorski** [comment]
@pietrosperoni  yup. agree! Need to clarify which are the key user stories for which the UI is optimised and then do the user interface design which will support them. 

I think how well the UI supports the key workflows *will* determine for many people whether they use the application or not.

**Comment by giovanisp** [comment]
+1
And as @vvorski demonstrated, that's another case where the imodal to vote is used wrongly.

**Comment by giovanisp** [comment]
Modal usage and workflow are already in the roadmap, please comment on those issues. Closing this as duplicate.
