### ISSUE TITLE
clicking repeatedly on a triangle voting, moving the votes of OTHER solutions

### ISSUE THREAD

**Issue by lazanna** [fairdemocracy/vilfredo-client#289]
clicking repeatedly on a triangle to vote for a specific solution, I managed to move my votes on OTHER solutions

**Comment by pietrosperoni** [comment]
Thanks. Sounds like a bug. Could you make a screencast of yourself doing it, so that it can be used by @derekpa to try to understand what happened? Unless you can explain clearly how to reproduce it .

By the way, I know there is a problem that when you click rapidly it shows multiple votes, but those are all multiple votes of the same proposal. And only the last one is recorded (I gather). Are you sure it is not this?

@giovanisp you might need to follow this as well :-)

**Comment by lazanna** [comment]
a screenshot would not understand anything
I have attached the video
https://drive.google.com/open?id=0B89_e4FVNy_zUThqY0FsRW1TRlU&authuser=0
it seems that it happens more frequently if you move the feedback from left to right

**Comment by giovanisp** [comment]
@derekpa from the video it seems similar to the "quick click" bug, but as you can see, it has moved also the grayed out votes on other proposals as well... Hence it should be treated as a new related bug.

**Comment by pietrosperoni** [comment]
Thanks @lazanna for the screencast (video about the screen). This is the kind of feedback that really helps us.

**Comment by derekpa** [comment]
@giovanisp Sure, but it was pretty obviously  the same bug.

**Comment by giovanisp** [comment]
Seems good here. @lazanna  do you still have this problem ?

**Comment by lazanna** [comment]
Yes, the problem occurs again ... only if you move the rating from right to left

**Comment by giovanisp** [comment]
@derekpa your turn :-)

**Comment by derekpa** [comment]
Makes no sense. Are we talking about the voting triangle and clicking?

**Comment by lazanna** [comment]
My test was made on vilfredo.org (not test.vilfredo.org).
The browser is Firefox 37.0.2.

**Comment by derekpa** [comment]
Fixes to issues are pushed to test, then the live site only gets the fixes on a new release - unless we add a hotfix.

So it should be working correctly on test at the moment.

Sorry for the confusion :-)

**Comment by giovanisp** [comment]
Closing for now. If it reappears we can reopen this.

**Comment by derekpa** [comment]
Its fixed! lazanna was testing on the live site, the fix is on test, as explained.

**Comment by giovanisp** [comment]
? I have indeed closed the issue. Not sure why you reopened this if it was fixed. You can close it if is really fixed.

**Comment by derekpa** [comment]
Not sure why i did either. Thought i'd just removed the wontfix label.
