### ISSUE TITLE
2 participants needed to end voting

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#290]
are we excluding the use-case where the user collects proposals and votes alone ?

![image](https://cloud.githubusercontent.com/assets/180794/6960770/dcda007c-d925-11e4-84d3-ff1a5f416a1e.png)

**Comment by pietrosperoni** [comment]
good question. Yes, it could be a good tool for people to ask for ideas, and then you just vote on all of them.
