### ISSUE TITLE
Add linear voting

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#293]
Connected to #292

**Comment by pietrosperoni** [comment]
:+1:

**Comment by giovanisp** [comment]
is this on core as well ?

**Comment by derekpa** [comment]
Yes, issues 73 and 74. I'll correct above.

**Comment by pietrosperoni** [comment]
It works so so. First of all it is hard to recognise. I would add a black line on contour to identify the part where people vote. Then the vote should not appear as a circle (that is a 2d representation for 2d voting, ie trangle) but as a vertical line. In fact we should, later order the proposal in a single column and connect each proposal to the position in the line. Something similar to this:

https://ciscogovclub.files.wordpress.com/2011/10/steve-jobs-timeline.jpg

Also on the right it should say Approve, and on the left it should say Reject. Or something equivalent.

Even ignoring the links between the proposal and the line, the other elements should be there, so I would say it is not ready, yet. Sorry

**Comment by pietrosperoni** [comment]
Ok, I tested it. Once a person votes it's ok. But it is REALLY difficult to realise how you vote. Because the line is white. Can we have a continuosly colored bar, like this one:

![screen shot 2015-05-08 at 18 36 18](https://cloud.githubusercontent.com/assets/1333674/7541917/c3c56b74-f5b0-11e4-831e-767f9df5ae44.png)

The problem with the triangle was that we needed it to go smooth on two directions, but here this is not happening, it is only one direction. Also the bar should not take the whole space, but only 3/4 or so. Leaving a bit of extra space around (unless the screen is way too small). 

And finally I would also take away the little bar below, which then becomes a bit confusing.

Oh, yes, also the button to vote should not be a triangle, ça va sans dire :-)

@giovanisp what are your thoughts? After all this is part of the UI.

**Comment by giovanisp** [comment]
Am I invited to a test linear voting? Can we all create more test questions and invite each other and write many test proposals and vote them? :-)

**Comment by pietrosperoni** [comment]
Ok, I invited you here: http://test.vilfredo.org/question/28

Have fun :-)

**Comment by giovanisp** [comment]
Sure you did? By clicking the link I get "Error: you have not been invited to participate in this question." Maybe relates to #311 @derekpa ?



Inviato da iPad

**Comment by pietrosperoni** [comment]
have you accepted the invitation? I cannot invite you again, so you are not in the list of the people I can invite but you are also not in the list of people who can participate. I would say you need to accept.

By the way, when someone is invited to a question, shouldn't he be able to see the question?

Maybe not the proposals before he accepts, but surely the text of the question yes

**Comment by giovanisp** [comment]
Waiting for a fix for the invitation (I think there is an issue for that). In the meantime I will accept manually.

**Comment by giovanisp** [comment]
@derekpa ... we need to get rid of the gray background here and color the voting bar. I couldn't guess that I was expected to vote in the white space...  Also, the "triangle vote" must be changed to another icon type (which makes more sense in both cases - triangle and linear).

![image](https://cloud.githubusercontent.com/assets/180794/7684205/95a2e146-fd84-11e4-8f20-f712df11e95d.png)

**Comment by pietrosperoni** [comment]
Ok, it's better than before. although I think it can be done much better having the continuous background

**Comment by pietrosperoni** [comment]
@derekpa what about the colored band I placed above. Is that not usable. Or should we wait until we move out of the modal phase?

**Comment by derekpa** [comment]
> I think it can be done much better having the continuous background

What do you mean?

**Comment by derekpa** [comment]
> what about the colored band I placed above. Is that not usable.

Huh? What coloured band?

**Comment by giovanisp** [comment]
The one on https://github.com/fairdemocracy/vilfredo-client/issues/293#issuecomment-100307381  And the proposals are the usual circles moved within the bar.

**Comment by giovanisp** [comment]
considering ok for linear voting. Enhancements go to 2.1

**Comment by pietrosperoni** [comment]
@giovanisp I object. This is not ok by any means. We cannot have people use this voting in this way. And this and few other things will be stopping Vilfredo from being used.

**Comment by giovanisp** [comment]
What is fundamental before saying " it works"? Let's add small enhancements into a patch if needed.

**Comment by derekpa** [comment]
OK, finally got rid of that weird bug. Looks like it might have been a bug in the svg library.

**Comment by pietrosperoni** [comment]
Yes, good! Thanks
