### ISSUE TITLE
BUG, same proposal appearing multiple times

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#297]
When I submit a proposal, and the server is slow, the result is that I click again and again and again, and at the end I end up submitting 25 times the next proposal. Surely one thing is to make the server more responsive, but another is that it should simply never accept two times the same proposal

![screen shot 2015-04-10 at 22 46 48](https://cloud.githubusercontent.com/assets/1333674/7098112/8506a390-dfd4-11e4-978b-c807c85d5b9a.png)

**Comment by giovanisp** [comment]
Haven't we already decided that the proposal title should be unique ??? We just need to enforce this on saving.

**Comment by pietrosperoni** [comment]
yes. unique among the proposals in the question (not unique among all the proposals written on the website)

**Comment by giovanisp** [comment]
what was the solution here, @derekpa  ?
@pietrosperoni do you still experiment this?

**Comment by pietrosperoni** [comment]
Hard to reproduce. At the time the system got stuck, now it is working but I don't know if it is because we are doing things better or it is just casually. In any case, no right now I cannot experience it again

**Comment by giovanisp** [comment]
Ok. To reopen if happens again.
