### ISSUE TITLE
There shouldn't be an edit or a delete button during the voting phase

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#298]
Example:

![screen shot 2015-04-10 at 23 00 10](https://cloud.githubusercontent.com/assets/1333674/7098177/2fefc642-dfd5-11e4-89a4-00fe5e8d4239.png)

**Comment by pietrosperoni** [comment]
At least the delete button might make sense. You see a proposal is double and you delete it. But the edit button does not even work:

![screen shot 2015-04-10 at 23 02 17](https://cloud.githubusercontent.com/assets/1333674/7098193/6624e27e-dfd5-11e4-8024-0035895b7e00.png)

**Comment by giovanisp** [comment]
I think both buttons should disappear in voting phase.
Duplicate proposals can be object of a future "merge proposals" feature so authors can agree to merge proposals before voting (or during if all voters are notified).

Inviato da iPad

**Comment by pietrosperoni** [comment]
merge proposals is very needed, but also very difficult to do. Because you basically need to select two proposals and then merge them. Maybe dropping one proposal over another could work? 
And then a box asking to the person if he really means it. If the answer is yes then the two proposals might be seen as alternative description of the same idea. Of course both authors need to agree.

**Comment by derekpa** [comment]
Yes I spotted this. Should be ok now.
