### ISSUE TITLE
Remove duplicate api calls

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#301]

**Comment by giovanisp** [comment]
not sure what is this about... why did you assigned it to me ?

**Comment by pietrosperoni** [comment]
@giovanisp I think this was assigned to you because you are the only one that can test it. @derekpa correctly is asking you to review his work, and I cannot do it.

**Comment by giovanisp** [comment]
Ok, got it. I need the API documentation completed to do that and the auto-generated dev.vilfredo.org/v2 with sample usage. Is this ok already?
I also need to know which duplicated calls were eliminated, since it was not described in the issue.

**Comment by derekpa** [comment]
Its ok giovani. I opened this myself to make a push. I removed some duplicates. I know the ons I saw are gone now so I can just close this. Didn't mean to assign to you.

**Comment by giovanisp** [comment]
Ok, thanks.
Let's get that document about the API ready and also on dev.vilfredo.org
I think that after 2.0.0 anyone should be able to make a simple client (we could open an issue to create a tutorial on this)...
