### ISSUE TITLE
rename "question type" to "proposal type"

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#307]
A question type "image" leads the user (also led me) to think you post an image as a question and then people comment if it is good or bad.

The best label for this feature is "Proposal Type", just rename "question type":

![image](https://cloud.githubusercontent.com/assets/180794/7539900/866934aa-f5aa-11e4-98a0-b6c674ea0d2b.png)

**Comment by giovanisp** [comment]
in the future we should support a "Image Question" where for instance I can post a mockup and receive feedback or proposals on how to make it better. Then, at the next generation, I post a "version 2" and the discussion continues until all agree it is a good design. Adding this as a feature.

**Comment by pietrosperoni** [comment]
This is an interesting idea @giovanisp , can you post it as a separate thread. The main question is: how can you set up a system where you can have a meta question, where the branches are questions, that then begets proposals. 
So how should we do a logo?
question 1: what about this? How can we improve it?
question 2: what about this? How can we improve it?
question 3: ...

In any case, not related to this issue. And yes this should have been proposal type accepted

**Comment by pietrosperoni** [comment]
Thanks @giovanisp for posting this as #308 .

Regarding here, yes, it should be proposal type .
