### ISSUE TITLE
Letting users know what power they have in each question (WAS: Can't write a proposal in generation 2)

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#312]
Hmm, apparently on generation 2 there is no button to propose new ideas.

**Comment by pietrosperoni** [comment]
Example: http://test.vilfredo.org/question/13

**Comment by giovanisp** [comment]
You probably do not have propose or vote permission. Here is the screen, @derekpa if this is the problem we need to make clearer what the invited user can do (by opening a new issue). Let us know why he can't write a proposal.

**Comment by pietrosperoni** [comment]
You mean you invited me to a question without giving me any power?

I have no words to express my feeling of betrayal. I thought you a friend ;-)

**Comment by pietrosperoni** [comment]
ok, works on a question where I invited myself to do everything :-P

**Comment by giovanisp** [comment]
So this issue becomes "letting users know which powers they have on every proposal?"

**Comment by pietrosperoni** [comment]
Ok, changed the title

**Comment by derekpa** [comment]
Yes, if you granted no write permissions the button won;t appear. 

Needs to be more descriptive.

**Comment by pietrosperoni** [comment]
"your soon to be ex friends invited you to view a question, but not to participate."

**Comment by pietrosperoni** [comment]
Maybe it is better to have the button greyed, and the explicative phrase when you go over it. ALthough it does not work on the ipad and tablets. So it should also written somwhere else.

**Comment by giovanisp** [comment]
@pietrosperoni can you check the question again ?  or invite me without voting or proposal permissions ?

**Comment by pietrosperoni** [comment]
I just went to the page and again it shows nothing. I will now make a qquestion and invite you with no power

**Comment by pietrosperoni** [comment]
Ok Derek and Giovani, you should have seen the question now:
http://test.vilfredo.org/question/35

**Comment by derekpa** [comment]
Gorgeous. I get this.

![screen shot 2015-05-22 at 18 07 54](https://cloud.githubusercontent.com/assets/1368533/7775736/a17cd9aa-00ad-11e5-9240-eed2808ae7f3.png)

**Comment by giovanisp** [comment]
Me too. Seems to work fine.
