### ISSUE TITLE
Proposal mage not displaying in inherited list

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#317]

**Comment by pietrosperoni** [comment]
Uh, can someone explain me what is this :-)

**Comment by derekpa** [comment]
Images were not displaying in the proposals of the inherited list which appear in generation 2+ due to missing code.

**Comment by pietrosperoni** [comment]
is a "proposal mage" somehow related to a wizard to write proposals?

**Comment by giovanisp** [comment]
Yes, those are proposals that can auto-solve the question. You don't have to do anything!

Inviato da iPad

**Comment by pietrosperoni** [comment]
:+1:  :-)
