### ISSUE TITLE
separate header and footer from templates 

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#33]
As of now header and footer in all 3 template files are equal. I suggest making one template for the header and other for the footer, so we can maintain code in one place and when we change something on the header or footer it will be done only once.
They could be parametric so things like "title", "meta description" and other text can be set by the client main template calling header and footer and customizing it as necessary.

**Comment by derekpa** [comment]
"we can always use some light server-side language for the client (php?)"

Well if we go that route right now it would make more sense to serve templates from python.

**Comment by giovanisp** [comment]
header and footer are separated from main template.
