### ISSUE TITLE
triangle is too high on some resolutions

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#6]
The triangle should match visible height of the screen device (better), to accomodate tablet users as well and other screen resolutions.

See the picture on 1366x
![clipboard01](https://cloud.githubusercontent.com/assets/180794/4699541/1e8bee5a-5842-11e4-8258-d2cb8dcb021e.png)

**Comment by pietrosperoni** [comment]
@giovanisp please test it now, as it was on your screen that it was too large, so in case @derekpa can close this

**Comment by giovanisp** [comment]
On demo I still see the triangle cut at the bottom. Can we make its width narrower and keep the aspect ratio? Probably widescreen monitor variations can lead to some pixels more in height. 


-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 02/01/2015  11:40  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] triangle is too high on some resolutions (#6) 

@giovanisp please test it now, as it was on your screen that it was too large, so in case @derekpa can close this

**Comment by giovanisp** [comment]
This is still to be done. The first step is measure if screen width > screen height  or not.  Then fix the aspect ratio on the triangle horizontally or vertically, according to this. So the triangle is always aligned.

**Comment by derekpa** [comment]
Thought it was done.

**Comment by derekpa** [comment]
Try that.

**Comment by giovanisp** [comment]
Seems better, but not what I intended. I will open a new issue for later enhancement.
