### ISSUE TITLE
place Web Analytics code in a template "analytics"

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#64]
Along with #63 , the current web analytics code should go into a separate template that the user can overwrite with her own code (Piwik, Webtrends, Google...) instead of being tied to what we are using.

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-53806407-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
</script>
```

**Comment by pietrosperoni** [comment]
@derekpa Are you still working on this, or can we close it? Or is there something we need to test?

**Comment by derekpa** [comment]
I think it's OK.

**Comment by pietrosperoni** [comment]
Please remember to assign it to the person that needs to review it.

**Comment by pietrosperoni** [comment]
@giovanisp can you please test this. You know more about it then me

**Comment by giovanisp** [comment]
done.
