### ISSUE TITLE
The send invitation in the demo does not work

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#67]
Just tried to send an invitation to Anthony, but nothing happened.
It either sends an invitation but does not change screen or it does not send the invitation at all.

Also demo.vilfredo.org should ONLY have the question on the name of the company.

**Comment by pietrosperoni** [comment]
I just tested it. 
I found a few bugs.
I sent myself an invite with a second email address. 
The email arrived. When I opened it I followed the link but was still logged in, and as a result I ended up being present in a question two times with the same name. 

![screen shot 2015-01-02 at 11 27 57](https://cloud.githubusercontent.com/assets/1333674/5595413/14db9cce-9272-11e4-9b58-51519ac9a2e5.png)


Would be interesting to find out what is going on at the DB side.

Then I copied the link and opened it in a different, not logged in, browser. So I had to reregister. And it sent me again the email address, and it asked me to test the address again. Even though I have already used that same address during the invitation.

So I think:
1) when a person receives an invitation mail, and he already is registered with another email address, he should be able to add this email address to his list of email addresses.
2) when a person receives an invitation and he is not registered he should be asked if he wants to register, and in case he uses the same email he used before we do not need to send him another email address.

I would say the first is really important, the second is just a minor annoyance.

@derekpa do I need to open two new issues or can we work on this one?

**Comment by giovanisp** [comment]
The first one is a "new feature" while number 2 is a bug, because the 
system knows if the person (email) you are inviting is already a 
registered user or not (or it can know easily if it doesn't yet control 
it).




Il 02.01.2015 02:31 Pietro Speroni ha scritto:

**Comment by pietrosperoni** [comment]
Ok, so for now is both an enhancement and a bug :-).

**Comment by giovanisp** [comment]
A bug that needs enhancement :-) 

-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 03/01/2015  11:07  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] The send invitation in the demo does not work
  (#67) 

Ok, so for now is both an enhancement and a bug :-).

**Comment by giovanisp** [comment]
@derekpa @pietrosperoni  are those 2 issues done?  If not, please create separate issues. This ticket was for "The send invitation in the demo does not work"  which now is OK, so needs to be closed.

**Comment by pietrosperoni** [comment]
I think this was done in #125
