### ISSUE TITLE
after successful registration, user should be auto logged-in 

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#71]
[usability enhancement] since the user provided email and password to register, the system should auto-login him to avoid forcing the user to re-insert his email/pass once again

**Comment by giovanisp** [comment]
Moved discussion to Vilfredo itself :) https://vilfredo.org/question/11

**Comment by pietrosperoni** [comment]
please invite @vvorski  to this. Also anybody else who wants to participate at the question Which Are Vilfredo Target Audience, should let us know:
@matiasbattocchia, @serapath, @Franz739

**Comment by pietrosperoni** [comment]
And please write ONE target audience per proposal

**Comment by giovanisp** [comment]
Send me private emails. We still can't invite by @ names :-) 
Makes me wonder if a new feature could be "ask to be invited" if in the future we will have publicly visible questions. 


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 06/02/2015  13:00  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] after successful registration, user should be auto logged-in  (#71) 
 
please invite @vvorski to this. Also anybody else who wants to participate at the question Which Are Vilfredo Target Audience, should let us know:
@matiasbattocchia, @serapath, @Franz739

**Comment by pietrosperoni** [comment]
"ask to be invited" sounds great

**Comment by vvorski** [comment]
"Request Invitation" sounds better in english.

**Comment by pietrosperoni** [comment]
yeah, those things shouldn't be decided by an Italian and a Brazilian.

**Comment by giovanisp** [comment]
+1 for "Request Invitation" I opened a new issue for that (#184).
