### ISSUE TITLE
define the security level for the client

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#74]
Related to #16, should the client implement SSL (be https-only) ? Which other security measures we want to have now (and later) ?

**Comment by giovanisp** [comment]
can we have this for api.vilfredo.org (or www.vilfredo.org) before 2.0.0-rc1 launch ?

**Comment by pietrosperoni** [comment]
Ok, I ordered the certificate for Vilfredo.org. It will only be valid for this domain and no subdomain. I am pretty sure they do not let other options, as this is a big source of revenue for them, but I can open a ticket if necessary. In any case even after it has been ordered I need to wait until it is active before I can activate the security hosting. So a bit of a patience

**Comment by pietrosperoni** [comment]
Ok, the certificate arrived, but so far it is not active, even though on the dreamhost site it says it is ok. Let's wait a bit as the info spreads across the network

![screen shot 2015-01-22 at 17 42 56](https://cloud.githubusercontent.com/assets/1333674/5859828/87cf3646-a25d-11e4-902b-9b560c4fc4fd.png)

**Comment by giovanisp** [comment]
It works fine for me https://www.vilfredo.org

**Comment by giovanisp** [comment]
@derekpa  it seems we can't make for https://api.vilfredo.org right ?  I'm opening a new issue for api and closing this.

**Comment by pietrosperoni** [comment]
correct. Unless I pay another 60$ ouch.
Also the API should point to some API and also that did not work @giovanisp

**Comment by giovanisp** [comment]
ok closed this as OK for SSL to vilfredo.org  and  waiting for #138.
