### ISSUE TITLE
When a person accepts an invitation, the person who invited him should be notified

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#75]
Probably receiving an email as well as seeing it on the question participatings page

**Comment by pietrosperoni** [comment]
Ok, let's make this actionable. Can we please have a notification in facebook or twitter style when someone joins a question? So something like a small that shows the number of notifications. And when you click on it a list of notifications. The people joining a question you opened will be one of those notifications. Others will be decided later (like when a question moves on, and when there is a question to a proposal you suggested, or when the pareto front have changed, or when you a keyplayer, and so on)

![screen shot 2015-01-02 at 11 38 08](https://cloud.githubusercontent.com/assets/1333674/5595460/97e9d012-9273-11e4-9346-9b7fcf674459.png)

**Comment by giovanisp** [comment]
@derekpa you can easily do it using Bootstrap badges elements. I suggest however for now just purchasing a cheap theme in a place like (http://themeforest.net/item/bucket-admin-bootstrap-3-responsive-flat-dashboard/6642985?WT.oss_phrase=bootstrap&WT.oss_rank=23&WT.z_author=ThemeBucket&WT.ac=search_list  see below some widget samples) so we have all these elements already graphically designed and responsive, until we nail down the user experience we want for version 2.x ;

![image](https://cloud.githubusercontent.com/assets/180794/5599049/d3436a86-92c0-11e4-9553-35f7a6aa03aa.png)

![image](https://cloud.githubusercontent.com/assets/180794/5599057/ef4cbf48-92c0-11e4-86eb-32694d9f3fb9.png)

![image](https://cloud.githubusercontent.com/assets/180794/5599064/0b7f073e-92c1-11e4-949c-fb766deb4d19.png)

![image](https://cloud.githubusercontent.com/assets/180794/5599093/7c5c0498-92c1-11e4-8d87-38974c38ebb2.png)

**Comment by pietrosperoni** [comment]
Ok @giovanisp let me know what should I buy

**Comment by pietrosperoni** [comment]
@giovanisp ?

**Comment by giovanisp** [comment]
let's put on hold until we decide about the UX (private talk). In the meantime I'll look around for free templates (if any).

**Comment by giovanisp** [comment]
@derekpa let's have the acceptance email notification here, first ?

**Comment by pietrosperoni** [comment]
The acceptance notification is already in place.
<img width="493" alt="screen shot 2016-04-30 at 18 03 27" src="https://cloud.githubusercontent.com/assets/1333674/14937395/e20666f8-0efd-11e6-8d56-c8742c2f0788.png">

**Comment by giovanisp** [comment]
Closing this and leaving #91 and #201 for notifications.
