### ISSUE TITLE
fix double activation message

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#79]
![image](https://cloud.githubusercontent.com/assets/180794/5331243/ea9b6bf6-7e21-11e4-8b95-078581be89b9.png)

Could be:

Error! This activation code was already used, has expired or does not exist.

then in the future we can guide te user to each of the three scenarios above and make the UI better (ie.: help on hijacked accounts; help on asking a new activation code; help on registering),

**Comment by derekpa** [comment]
OK, I mis-spoke. 

"Sorry we have no record of you registration. Please email support or register again." is returned correctly where there is no user found in the DB. 

This would appear on nightly when the DB is reset.

"This activation code was already used, has expired or does not exist." is correctly returned when there is no validation record found.

**Comment by giovanisp** [comment]
ok please advise if it done for 2.0.0-rc1 or has to be postponed.

**Comment by derekpa** [comment]
Done.
