### ISSUE TITLE
performance glitches appear

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#83]
as per #76 @pietrosperoni reported performance glitches and up to 10s time waiting.

**Comment by pietrosperoni** [comment]
@giovanisp I do not have anything to do on this. I assign this to you so you can decide if it should be closed or should it be assigned to @derekpa

**Comment by giovanisp** [comment]
it goes to @derekpa :  "After load (4s) until the full load (10s) there are several calls to the same resource "results", all of them with the same content. Are we doing that on purpose or is it a bug?"   See the above network timeline. We have too many calls that result in identical responses. Is that on purpose? Why ?

**Comment by giovanisp** [comment]
I added GZIP rules in the internal htaccess file.
Check our ratings: https://developers.google.com/speed/pagespeed/insights/?hl=en&utm_source=wmx&utm_campaign=wmx_otherlinks&url=https%3A%2F%2Fwww.vilfredo.org%2F&tab=desktop

**Comment by giovanisp** [comment]
No improvements. Skipped to final.

**Comment by giovanisp** [comment]
@derekpa I have added "async" to all bottom JS files in the index.html page to test if it loads faster and without problems with knowckout... Let's see...

**Comment by giovanisp** [comment]
Skipping to next. This is always ongoing. @derekpa So the solution is to identify the main files that must be loaded first and which other files can be loaded async.

**Comment by derekpa** [comment]
After all he discussion, the simple answer was yes, there were repeat calls being made, so I've removed them :-)
