### ISSUE TITLE
The results should only be visible after people have voted.

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#85]
This is the first of the feedback from my father.

At the moment the triangle with the result is placed as soon as someone opens the page. This is confusing (especially because people do not know what the triangle means). Also if people were to understand the triangle it would have a bias effect, affecting how people voted. Also later in the voting process it was clear how my father did not realise he did not vote for all the proposals. So my suggestion would be to have all the proposals that need to be voted *before* the results. Then each proposal evaluated, once evaluated would disappear from before and appear under.

There are several enhancements that can be made following my father feedback, but this is a single simple one that would greatly enhance the experience, and make sure all proposals get voted.

**Comment by pietrosperoni** [comment]
TO be tested, please share what you have done @derekpa

**Comment by derekpa** [comment]
I made changes in commit 6776d39 (forgot to add the issue number) so results map and voting graphs are only displayed once all proposals have been voted for.

**Comment by pietrosperoni** [comment]
Could not test it because of #118 Voting is not working.

**Comment by pietrosperoni** [comment]
Ok, it works. Thanks
