### ISSUE TITLE
Triangle should look nicer

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#86]
This is related to #6 but it goes further. I have made a short video (only 8.5 MB) to explain well the problems there are with the triangle right now:

https://dl.dropboxusercontent.com/u/2754299/TriangleAndZoom.mov

Basically, 
1) The triangle is not centred (at least on my configuration, macbook pro, Chrome).
2) The triangle is too short on the horizontal side. The vertical is perfect. So we are using the wrong ratio at least for this machine. Not sure how this changes on other machines
3) the grey rectangle is perfect in its dimensions, but the triangle does not finish where the grey triangle finishes
4) when a person sees the triangle at different zoom levels (zooming in or out of a page, for example if he has a very big monitor, or a very small one, or he cannot see very well) the triangle size does not change in a smooth way.

Note also that there is no effective need to keep a grey background around the triangle, so taking that away might not solve the ratio of the triangle, but at least make it look less ugly.

**Comment by pietrosperoni** [comment]
It was always the zoom problem. The problem was that the triangle did not look nice in my screen. And the reason (in retrospect I realise) is that I practically never keep the 100% zoom but usually the 120% zoom so I do not need glasses. It's just that it was not clear at the time.

**Comment by giovanisp** [comment]
I try to do that whenever I can. You guys feel free to split conversations as well and link similar issues. 



-------- Messaggio originale --------
Da: Derek Paterson <notifications@github.com> 
Data: 31/12/2014  17:05  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] Triangle should look nicer (#86) 

I think so :-)

Actually a lot of issues seem to turn into threads where speculative future work is discussed and so become longer and longer to-do lists, at which point it's a bit difficult to close the issue. Would be good if issue 'threads' could be split at some point into other issues leaving the original issue more focussed and therefore closable.

**Comment by giovanisp** [comment]
closed issue for "looking nicer" and opened #137 for the zoom bug.
