### ISSUE TITLE
Move everything from agilefant to github

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#9]
Move everything from agilefant to github issues

**Comment by giovanisp** [comment]
is agilefant now "closed" or does it holds any other valuable information?
Can we close this issue ?

**Comment by pietrosperoni** [comment]
Good question. There are some vague ideas left. Things I don't want to put here not to pollute this space with vagueness. On the other side it has value as notes for me. So I would say let's close this. And then from time to time I might copy one idea when the time is ripe. Basically the topics that are there are:
How do you handle the move on from one generation to the next
how to handle a system with no generations all together.

The first will be very soon. In the next version I hope. The next one will be a long way away.

I would say let's close this and I keep agilefant as my private space

**Comment by giovanisp** [comment]
Ok for closing.
Why don't you move these two "how" questions into vilfredo 2.0.0-rc1 ?

**Comment by pietrosperoni** [comment]
Because we are going another way. So those are many small to do but for a path we will probably not take at all, and do something alternative. But things can still go bad, and we might need to recover them.

Ok, I close
