### ISSUE TITLE
Real time notifications on top navbar are important

### ISSUE THREAD

**Issue by giovanisp** [fairdemocracy/vilfredo-client#91]
Not sure if we can make to 2.0.0 but I found the need to have a notification button on the top navbar that tells me if someone commented or made a question on my proposals, so I could click and reply, instead of looking at each proposal's icons.

**Comment by pietrosperoni** [comment]
This is very important as this permits a group of people to work on a topic together.

**Comment by pietrosperoni** [comment]
Opened question 49 on Vilfredo

**Comment by giovanisp** [comment]
Closing this as duplicate of #201 , the vilfredo question no longer exists.
