### ISSUE TITLE
Set min proposal title length to 2

### ISSUE THREAD

**Issue by derekpa** [fairdemocracy/vilfredo-client#97]

**Comment by pietrosperoni** [comment]
Explanation. 
Hi @giovanisp , with @derekpa we decided that too often a short title was just not accepted while it was a fully acceptable one. So it has to be the author's responsibility to have a good title.

**Comment by giovanisp** [comment]
Ok. It could be a client parameter, so in the future who creates the question can decide these minor rules. 


-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 02/01/2015  09:29  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: Re: [vilfredo-client] Set min proposal title length to 2 (#97) 

Explanation. 
Hi @giovanisp , with @derekpa we decided that too often a short title was just not accepted while it was a fully acceptable one. So it has to be the author's responsibility to have a good title.

**Comment by pietrosperoni** [comment]
It could but it unnecessarily makes opening a question more difficult.

**Comment by giovanisp** [comment]
I mean not for use right now. Using pogressive disclosure in the future 
(http://en.wikipedia.org/wiki/Progressive_disclosure) can allow us for 
complex setups and experiments just by tweaking sw parameters, instead 
of hardoding lenghts and numbers in the core/client.
I still opt to make all these parameters easily changeable in the conf 
file.



Il 02.01.2015 02:32 Pietro Speroni ha scritto:

**Comment by pietrosperoni** [comment]
Yes, this is a great idea. Let me add it as a Maybesomeday
