### ISSUE TITLE
Page disappearing

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#99]
When I enter into a question on nightly it disappears. I made a small video. This is obviously a bug.

You will find the video here:
https://dl.dropboxusercontent.com/u/2754299/disappearances.mov

**Comment by derekpa** [comment]
Might be connected to #98. Want to try again?

**Comment by pietrosperoni** [comment]
Hmm now it seems to be working :-) . Thanks
